// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DailyTraffic {
    /**
     * Creates a new DailyTraffic instance.
     * @param {Partial<DailyTraffic>} [$$source = {}] - The source object to create the DailyTraffic.
     */
    constructor($$source = {}) {
        if (!("date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["date"] = "";
        }
        if (!("uplink" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uplink"] = 0;
        }
        if (!("downlink" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downlink"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyTraffic instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DailyTraffic}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DailyTraffic(/** @type {Partial<DailyTraffic>} */($$parsedSource));
    }
}

export class GeoSettings {
    /**
     * Creates a new GeoSettings instance.
     * @param {Partial<GeoSettings>} [$$source = {}] - The source object to create the GeoSettings.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("assetDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["assetDir"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["useGHProxy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["logLevel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["dnsHosts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dnsServers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["ui"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GeoSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GeoSettings}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dnsHosts" in $$parsedSource) {
            $$parsedSource["dnsHosts"] = $$createField4_0($$parsedSource["dnsHosts"]);
        }
        if ("dnsServers" in $$parsedSource) {
            $$parsedSource["dnsServers"] = $$createField5_0($$parsedSource["dnsServers"]);
        }
        if ("ui" in $$parsedSource) {
            $$parsedSource["ui"] = $$createField6_0($$parsedSource["ui"]);
        }
        return new GeoSettings(/** @type {Partial<GeoSettings>} */($$parsedSource));
    }
}

/**
 * Mode selects what xray-core listens on: a local HTTP/SOCKS proxy
 * ("proxy") or a TUN adapter capturing all system traffic ("tun").
 * @typedef {string} Mode
 */

/**
 * Predefined constants for type Mode.
 * @namespace
 */
export const Mode = {
    ModeProxy: "proxy",
    ModeTUN: "tun",
};

export class OutboundRule {
    /**
     * Creates a new OutboundRule instance.
     * @param {Partial<OutboundRule>} [$$source = {}] - The source object to create the OutboundRule.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("whitelistDomains" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["whitelistDomains"] = [];
        }
        if (!("whitelistIPs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["whitelistIPs"] = [];
        }
        if (!("blacklistDomains" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["blacklistDomains"] = [];
        }
        if (!("blacklistIPs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["blacklistIPs"] = [];
        }
        if (!("proxyDomains" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["proxyDomains"] = [];
        }
        if (!("proxyIPs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["proxyIPs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutboundRule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OutboundRule}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("whitelistDomains" in $$parsedSource) {
            $$parsedSource["whitelistDomains"] = $$createField3_0($$parsedSource["whitelistDomains"]);
        }
        if ("whitelistIPs" in $$parsedSource) {
            $$parsedSource["whitelistIPs"] = $$createField4_0($$parsedSource["whitelistIPs"]);
        }
        if ("blacklistDomains" in $$parsedSource) {
            $$parsedSource["blacklistDomains"] = $$createField5_0($$parsedSource["blacklistDomains"]);
        }
        if ("blacklistIPs" in $$parsedSource) {
            $$parsedSource["blacklistIPs"] = $$createField6_0($$parsedSource["blacklistIPs"]);
        }
        if ("proxyDomains" in $$parsedSource) {
            $$parsedSource["proxyDomains"] = $$createField7_0($$parsedSource["proxyDomains"]);
        }
        if ("proxyIPs" in $$parsedSource) {
            $$parsedSource["proxyIPs"] = $$createField8_0($$parsedSource["proxyIPs"]);
        }
        return new OutboundRule(/** @type {Partial<OutboundRule>} */($$parsedSource));
    }
}

export class OutboundSettings {
    /**
     * Creates a new OutboundSettings instance.
     * @param {Partial<OutboundSettings>} [$$source = {}] - The source object to create the OutboundSettings.
     */
    constructor($$source = {}) {
        if (!("rules" in $$source)) {
            /**
             * @member
             * @type {OutboundRule[]}
             */
            this["rules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutboundSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OutboundSettings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField0_0($$parsedSource["rules"]);
        }
        return new OutboundSettings(/** @type {Partial<OutboundSettings>} */($$parsedSource));
    }
}

export class ServerTraffic {
    /**
     * Creates a new ServerTraffic instance.
     * @param {Partial<ServerTraffic>} [$$source = {}] - The source object to create the ServerTraffic.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("uplink" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uplink"] = 0;
        }
        if (!("downlink" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downlink"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerTraffic instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerTraffic}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerTraffic(/** @type {Partial<ServerTraffic>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateStopped: "stopped",
    StateStarting: "starting",
    StateRunning: "running",
    StateError: "error",
};

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["server"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Mode | undefined}
             */
            this["mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

export class Traffic {
    /**
     * Creates a new Traffic instance.
     * @param {Partial<Traffic>} [$$source = {}] - The source object to create the Traffic.
     */
    constructor($$source = {}) {
        if (!("uplink" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uplink"] = 0;
        }
        if (!("downlink" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downlink"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TrafficHistory | null | undefined}
             */
            this["history"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Traffic instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Traffic}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField2_0($$parsedSource["history"]);
        }
        return new Traffic(/** @type {Partial<Traffic>} */($$parsedSource));
    }
}

export class TrafficHistory {
    /**
     * Creates a new TrafficHistory instance.
     * @param {Partial<TrafficHistory>} [$$source = {}] - The source object to create the TrafficHistory.
     */
    constructor($$source = {}) {
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {TrafficTotals}
             */
            this["total"] = (new TrafficTotals());
        }
        if (!("daily" in $$source)) {
            /**
             * @member
             * @type {DailyTraffic[]}
             */
            this["daily"] = [];
        }
        if (!("servers" in $$source)) {
            /**
             * @member
             * @type {ServerTraffic[]}
             */
            this["servers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrafficHistory instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrafficHistory}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("total" in $$parsedSource) {
            $$parsedSource["total"] = $$createField0_0($$parsedSource["total"]);
        }
        if ("daily" in $$parsedSource) {
            $$parsedSource["daily"] = $$createField1_0($$parsedSource["daily"]);
        }
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField2_0($$parsedSource["servers"]);
        }
        return new TrafficHistory(/** @type {Partial<TrafficHistory>} */($$parsedSource));
    }
}

export class TrafficTotals {
    /**
     * Creates a new TrafficTotals instance.
     * @param {Partial<TrafficTotals>} [$$source = {}] - The source object to create the TrafficTotals.
     */
    constructor($$source = {}) {
        if (!("uplink" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uplink"] = 0;
        }
        if (!("downlink" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["downlink"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrafficTotals instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrafficTotals}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrafficTotals(/** @type {Partial<TrafficTotals>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = OutboundRule.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = TrafficHistory.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = TrafficTotals.createFrom;
const $$createType8 = DailyTraffic.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = ServerTraffic.createFrom;
const $$createType11 = $Create.Array($$createType10);
