// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Server is one saved proxy profile, storage- and UI-agnostic.
 */
export class Server {
    /**
     * Creates a new Server instance.
     * @param {Partial<Server>} [$$source = {}] - The source object to create the Server.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * vmess, vless, trojan, shadowsocks
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * vmess/vless
             * @member
             * @type {string | undefined}
             */
            this["uuid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * trojan/ss
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ss cipher
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * network, tls, sni, path, etc.
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["extra"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["outboundRuleIds"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Server}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField8_0($$parsedSource["extra"]);
        }
        if ("outboundRuleIds" in $$parsedSource) {
            $$parsedSource["outboundRuleIds"] = $$createField9_0($$parsedSource["outboundRuleIds"]);
        }
        return new Server(/** @type {Partial<Server>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
