// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ProxyConfig describes the three system proxy endpoints independently.
 */
export class ProxyConfig {
    /**
     * Creates a new ProxyConfig instance.
     * @param {Partial<ProxyConfig>} [$$source = {}] - The source object to create the ProxyConfig.
     */
    constructor($$source = {}) {
        if (!("httpHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["httpHost"] = "";
        }
        if (!("httpPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpPort"] = 0;
        }
        if (!("httpsHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["httpsHost"] = "";
        }
        if (!("httpsPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["httpsPort"] = 0;
        }
        if (!("socksHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["socksHost"] = "";
        }
        if (!("socksPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["socksPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyConfig(/** @type {Partial<ProxyConfig>} */($$parsedSource));
    }
}

/**
 * ProxyStatus is the current operating-system proxy state.
 */
export class ProxyStatus {
    /**
     * Creates a new ProxyStatus instance.
     * @param {Partial<ProxyStatus>} [$$source = {}] - The source object to create the ProxyStatus.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {ProxyConfig}
             */
            this["config"] = (new ProxyConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyStatus}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new ProxyStatus(/** @type {Partial<ProxyStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ProxyConfig.createFrom;
