// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails bound struct: every exported method on it becomes
 * callable from the frontend via the generated JS bridge.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "./internal/system/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "./internal/update/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as xray$0 from "./internal/xray/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profile$0 from "./pkg/profile/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} link
 * @returns {$CancellablePromise<profile$0.Server>}
 */
export function AddProfileFromLink(link) {
    return $Call.ByID(4262038085, link).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddSubscription fetches a subscription URL (the standard V2RayN/
 * V2RayNG/Shadowrocket-style base64 link list most providers publish)
 * and adds every server it can parse out of it. It succeeds as long as
 * at least one server was added, even if some entries in the
 * subscription couldn't be parsed.
 * @param {string} subURL
 * @returns {$CancellablePromise<profile$0.Server[]>}
 */
export function AddSubscription(subURL) {
    return $Call.ByID(2490111669, subURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ApplyUpdate downloads and installs the build found by the most recent
 * CheckForUpdate, then relaunches. On success this does not return: the
 * new process has already started and this one is about to exit. It only
 * returns when something failed before that point.
 * @returns {$CancellablePromise<void>}
 */
export function ApplyUpdate() {
    return $Call.ByID(4175318290);
}

/**
 * AutoStartEnabled reports whether Krab is registered to start when the
 * current user signs in.
 * @returns {$CancellablePromise<boolean>}
 */
export function AutoStartEnabled() {
    return $Call.ByID(305882107);
}

/**
 * CheckForUpdate queries GitHub Releases for a newer build. The result is
 * cached on the App so a subsequent ApplyUpdate doesn't need the frontend
 * to round-trip the (unexported) download URL back to us.
 * @returns {$CancellablePromise<update$0.Info>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2347956003).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearSystemProxy() {
    return $Call.ByID(4041061133);
}

/**
 * Connect starts xray-core against the given server profile in the given
 * mode ("proxy" or "tun"; anything else is treated as "proxy"). TUN mode
 * is currently Windows-only and requires the process to already be
 * running elevated -- see Platform/IsElevated/RestartElevated below.
 * killSwitch, when true, blocks all outbound traffic except Krab's own
 * (which is how xray itself reaches the VPN server) and loopback while
 * connected -- see internal/system/killswitch_windows.go. It's currently
 * Windows-only and needs the same elevation as TUN mode.
 * @param {string} serverID
 * @param {string} mode
 * @param {boolean} killSwitch
 * @returns {$CancellablePromise<void>}
 */
export function Connect(serverID, mode, killSwitch) {
    return $Call.ByID(164877153, serverID, mode, killSwitch);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteOutboundRule(id) {
    return $Call.ByID(929884744, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProfile(id) {
    return $Call.ByID(2457157279, id);
}

/**
 * DeleteSubscriptionGroup removes every server that was imported from
 * the same subscription (same extra.subGroup id).
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSubscriptionGroup(groupID) {
    return $Call.ByID(2649572894, groupID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(3864343059);
}

/**
 * EditSubscription renames a subscription group and/or changes its URL.
 * A changed URL takes effect on the next sync.
 * @param {string} groupID
 * @param {string} name
 * @param {string} subURL
 * @returns {$CancellablePromise<void>}
 */
export function EditSubscription(groupID, name, subURL) {
    return $Call.ByID(3892794040, groupID, name, subURL);
}

/**
 * @returns {$CancellablePromise<xray$0.GeoSettings>}
 */
export function GeoSettings() {
    return $Call.ByID(2240918607).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * IsElevated reports whether Krab is currently running with administrator
 * privileges (relevant to TUN mode, which needs them).
 * @returns {$CancellablePromise<boolean>}
 */
export function IsElevated() {
    return $Call.ByID(2510389459);
}

/**
 * @returns {$CancellablePromise<profile$0.Server[]>}
 */
export function ListProfiles() {
    return $Call.ByID(1957526603).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<xray$0.OutboundSettings>}
 */
export function OutboundSettings() {
    return $Call.ByID(2204162056).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * PingServer measures a server's delay in ms. mode is "tcp", "http" or
 * "real" (a real request through a temporary xray-core instance).
 * @param {string} id
 * @param {string} mode
 * @returns {$CancellablePromise<number>}
 */
export function PingServer(id, mode) {
    return $Call.ByID(3414229430, id, mode);
}

/**
 * Platform reports the OS Krab is running on, so the frontend can hide
 * the TUN mode option where it isn't supported yet.
 * @returns {$CancellablePromise<string>}
 */
export function Platform() {
    return $Call.ByID(515534666);
}

/**
 * RecentLog returns the tail of xray-core's own error log, for diagnosing a
 * connection that reports "running" but isn't actually routing traffic.
 * @returns {$CancellablePromise<string>}
 */
export function RecentLog() {
    return $Call.ByID(2759323868);
}

/**
 * RefreshSubscription re-fetches the subscription that a given server
 * group was originally imported from, replacing that group's servers
 * with the freshly parsed list (same group ID, so the UI's expand/
 * collapse state and position don't reset).
 * @param {string} groupID
 * @returns {$CancellablePromise<profile$0.Server[]>}
 */
export function RefreshSubscription(groupID) {
    return $Call.ByID(1647974629, groupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<profile$0.Server>}
 */
export function RenameProfile(id, name) {
    return $Call.ByID(1067637764, id, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RestartElevated relaunches Krab with a UAC prompt and exits this
 * process on success. Only returns when the relaunch itself failed
 * (including the user cancelling the prompt).
 * @returns {$CancellablePromise<void>}
 */
export function RestartElevated() {
    return $Call.ByID(2840047614);
}

/**
 * @param {xray$0.GeoSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveGeoSettings(settings) {
    return $Call.ByID(2192155920, settings);
}

/**
 * @param {xray$0.OutboundRule} rule
 * @returns {$CancellablePromise<void>}
 */
export function SaveOutboundRule(rule) {
    return $Call.ByID(1444683690, rule);
}

/**
 * @param {xray$0.OutboundSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveOutboundSettings(settings) {
    return $Call.ByID(2519861881, settings);
}

/**
 * SaveProfile stores a server from the editor: a new one when it has no ID
 * yet (added manually), otherwise an update of the existing one.
 * @param {profile$0.Server} server
 * @returns {$CancellablePromise<profile$0.Server>}
 */
export function SaveProfile(server) {
    return $Call.ByID(406053493, server).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveSystemProxyConfig persists the ports used by the next Xray connection
 * without changing the operating system's current proxy state.
 * @param {system$0.ProxyConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveSystemProxyConfig(config) {
    return $Call.ByID(377826085, config);
}

/**
 * SetAutoStart enables or disables starting Krab when the current user signs in.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoStart(enabled) {
    return $Call.ByID(2839137916, enabled);
}

/**
 * SetSystemProxy applies proxy settings only on explicit user request.
 * @param {system$0.ProxyConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SetSystemProxy(config) {
    return $Call.ByID(2213240030, config);
}

/**
 * SetWindowTheme keeps the native window chrome in sync with the web UI.
 * CSS alone cannot change the macOS title bar or the Windows window frame.
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowTheme(theme) {
    return $Call.ByID(2182416316, theme);
}

/**
 * ShareLink returns a server's standard share link (vless://, vmess://,
 * trojan://, ss://) for copying into another client.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ShareLink(id) {
    return $Call.ByID(547990480, id);
}

/**
 * ShareSubscription returns the share links of every server in a
 * subscription group, one per line -- a plain link list any client can
 * import, even when the original subscription URL is private.
 * @param {string} groupID
 * @returns {$CancellablePromise<string>}
 */
export function ShareSubscription(groupID) {
    return $Call.ByID(3940248393, groupID);
}

/**
 * @returns {$CancellablePromise<xray$0.Status>}
 */
export function Status() {
    return $Call.ByID(2836613335).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<system$0.ProxyStatus>}
 */
export function SystemProxyStatus() {
    return $Call.ByID(1817371390).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * TestConnection makes an actual HTTP request through the local xray HTTP
 * inbound so a "running" status that isn't really routing traffic (bad
 * outbound handshake, unreachable server, etc.) surfaces a concrete error
 * instead of looking like nothing is wrong. It hits Cloudflare's own
 * trace endpoint rather than a generic 204 check, since that response
 * includes the client IP and country as Cloudflare's edge sees them --
 * i.e. exactly what a site would see you connecting from.
 * @returns {$CancellablePromise<$models.TestResult>}
 */
export function TestConnection() {
    return $Call.ByID(1257240193).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Traffic returns the current session's cumulative uplink/downlink byte
 * counters, for the live traffic display. The frontend polls this and
 * diffs successive calls to derive a speed.
 * @returns {$CancellablePromise<xray$0.Traffic>}
 */
export function Traffic() {
    return $Call.ByID(1564445326).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * UpdateGeoData downloads geoip.dat and geosite.dat into the configured
 * asset directory, optionally through gh-proxy.com.
 * @param {string} assetDir
 * @param {boolean} useGHProxy
 * @returns {$CancellablePromise<void>}
 */
export function UpdateGeoData(assetDir, useGHProxy) {
    return $Call.ByID(1100346601, assetDir, useGHProxy);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(2431199839);
}

/**
 * XrayVersion returns the embedded xray-core version, for the About panel.
 * @returns {$CancellablePromise<string>}
 */
export function XrayVersion() {
    return $Call.ByID(1154261691);
}

// Private type creation functions
const $$createType0 = profile$0.Server.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = update$0.Info.createFrom;
const $$createType3 = xray$0.GeoSettings.createFrom;
const $$createType4 = xray$0.OutboundSettings.createFrom;
const $$createType5 = xray$0.Status.createFrom;
const $$createType6 = system$0.ProxyStatus.createFrom;
const $$createType7 = $models.TestResult.createFrom;
const $$createType8 = xray$0.Traffic.createFrom;
