// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * TestResult is what the Test button reports: the exit IP the target site
 * actually sees (i.e. the VPN server's IP, not Krab's), the two-letter
 * country code Cloudflare's edge resolved it to, and the real round-trip
 * time of the whole request (DNS/TCP/TLS/HTTP) made through the tunnel.
 */
export class TestResult {
    /**
     * Creates a new TestResult instance.
     * @param {Partial<TestResult>} [$$source = {}] - The source object to create the TestResult.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("country" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["country"] = "";
        }
        if (!("delayMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["delayMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestResult(/** @type {Partial<TestResult>} */($$parsedSource));
    }
}
