import { Browser, Clipboard, Events } from '@wailsio/runtime'
import { useEffect, useMemo, useRef, useState } from 'react'
import logo from '../../build/appicon.png'
import { LANGUAGES, getDir, makeT } from './i18n'
import LogsView from './views/LogsView'
import OutboundSettingsView from './views/OutboundSettingsView'
import ProxySettingsView from './views/ProxySettingsView'
import StatsView from './views/StatsView'

const noTextAssist = { autoCapitalize: 'none', autoCorrect: 'off', spellCheck: false }

// This module is generated by Wails ("wails dev" / "wails build") from the
// exported methods on the App struct in app.go. It won't exist until then.
import {
  AddProfileFromLink,
  AddSubscription,
  ApplyUpdate,
  AutoStartEnabled,
  CheckForUpdate,
  ClearSystemProxy,
  Connect,
  DeleteProfile,
  DeleteOutboundRule,
  DeleteSubscriptionGroup,
  Disconnect,
  EditSubscription,
  GeoSettings,
  IsElevated,
  ListProfiles,
  OutboundSettings,
  PingServer,
  Platform,
  RecentLog,
  RefreshSubscription,
  RenameProfile,
  RestartElevated,
  SaveGeoSettings,
  SaveOutboundRule,
  SaveProfile,
  SaveSystemProxyConfig,
  SetSystemProxy,
  SetAutoStart,
  SetWindowTheme,
  ShareLink,
  ShareSubscription,
  Status,
  SystemProxyStatus,
  TestConnection,
  Traffic,
  UpdateGeoData,
  Version,
  XrayVersion,
} from '../bindings/github.com/krabt/krab/app'

function errorText(err) {
  if (!err) return 'Unknown error'
  if (typeof err === 'string') return err
  if (err.message) return err.message
  return String(err)
}

async function copyText(text) {
  try {
    await Clipboard.SetText(text)
  } catch {
    await navigator.clipboard.writeText(text)
  }
}

function openExternal(url) {
  Browser.OpenURL(url).catch(() => window.open(url, '_blank'))
}

// Windows' emoji font (Segoe UI Emoji) doesn't render regional-indicator
// flag emoji -- it falls back to showing the two letters instead. Use an
// actual flag image so this looks right cross-platform.
function flagIconUrl(countryCode) {
  if (!countryCode || countryCode.length !== 2) return ''
  return `https://flagcdn.com/24x18/${countryCode.toLowerCase()}.png`
}

function Icon({ path, className = 'w-5 h-5' }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <path d={path} />
    </svg>
  )
}

const icons = {
  globe: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM3.6 9h16.8M3.6 15h16.8M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18',
  plus: 'M12 5v14M5 12h14',
  search: 'm21 21-4.3-4.3M18.5 11a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z',
  trash: 'M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13M10 11v6M14 11v6',
  pencil: 'M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4Z',
  power: 'M12 3v9M18.4 6.6a8.5 8.5 0 1 1-12.8 0',
  gauge: 'M12 8v4l3 2M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Z',
  terminal: 'm5 6 5 5-5 5M13 17h6',
  info: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM12 16v-5h-1M11.94 8h.01',
  x: 'M6 6l12 12M18 6 6 18',
  sun: 'M12 17a5 5 0 1 0 0-10 5 5 0 0 0 0 10ZM12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4',
  moon: 'M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z',
  download: 'M12 3v12m0 0-4-4m4 4 4-4M4 21h16',
  shield: 'M12 3 5 6v5c0 4.5 3 7.7 7 9 4-1.3 7-4.5 7-9V6l-7-3Z',
  router: 'M4 15h16v4H4z M4 19v0 M20 19v0 M8 15V9a4 4 0 0 1 8 0v6 M12 3v2',
  share: 'M4 12v7a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-7M16 6l-4-4-4 4M12 2v13',
  translate: 'M4 5h7M9 3v2M9 5a10.4 10.4 0 0 1-4 8M3 9c0 3 3 5.5 6 6M12 20l4-9 4 9M13.5 17h5',
  language: 'M4 4h16v12H9l-5 4V4Zm4 4h8M8 12h5',
  settings: 'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7ZM19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.12 2.12-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.04 1.57V20h-3v-.08a1.7 1.7 0 0 0-1.04-1.57 1.7 1.7 0 0 0-1.88.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 7 14.7a1.7 1.7 0 0 0-1.57-1.04H5v-3h.08A1.7 1.7 0 0 0 6.65 9.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.12-2.12.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 11.35 4.4V4h3v.08a1.7 1.7 0 0 0 1.04 1.57 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.12 2.12-.06.06a1.7 1.7 0 0 0-.34 1.88 1.7 1.7 0 0 0 1.57 1.04H21v3h-.08A1.7 1.7 0 0 0 19.4 15Z',
  outbound: 'M4 12h13M13 7l5 5-5 5M4 5h5M4 19h5',
  copy: 'M8 8h11v11H8zM5 16H4V5h11v1',
  chart: 'M4 19V9m6 10V5m6 14v-7m4 7H2',
}

const defaultProxyConfig = {
  httpHost: '127.0.0.1', httpPort: 5889,
  httpsHost: '127.0.0.1', httpsPort: 5889,
  socksHost: '127.0.0.1', socksPort: 5888,
}

function normalizeProxyPorts(config, invalidMessage) {
  const normalized = { ...config }
  for (const key of ['httpPort', 'httpsPort', 'socksPort']) {
    const value = String(config[key] ?? '').trim()
    if (!/^\d+$/.test(value)) throw new Error(invalidMessage)
    const port = Number(value)
    if (!Number.isSafeInteger(port) || port < 1 || port > 65535) throw new Error(invalidMessage)
    normalized[key] = port
  }
  return normalized
}

function proxyEndpointSummary(config) {
  const current = { ...defaultProxyConfig, ...(config || {}) }
  const http = `${current.httpHost}:${current.httpPort}`
  const https = `${current.httpsHost}:${current.httpsPort}`
  const socks = `${current.socksHost}:${current.socksPort}`
  return http === https
    ? `HTTP/HTTPS ${http} · SOCKS5 ${socks}`
    : `HTTP ${http} · HTTPS ${https} · SOCKS5 ${socks}`
}

function StatusDot({ state }) {
  const color =
    state === 'running' ? 'bg-emerald-400' : state === 'starting' ? 'bg-amber-400' : state === 'error' ? 'bg-red-400' : 'bg-neutral-600'
  return <span className={`inline-block w-2 h-2 rounded-full ${color}`} />
}

function IconButton({ onClick, title, active, label, children }) {
  return (
    <button
      className={`w-full h-11 px-3 rounded-lg flex items-center gap-3 transition-colors text-xs ${active ? 'bg-gradient-to-r from-violet-600/25 to-transparent text-violet-200 border-l-2 border-[var(--accent)]' : 'text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)]'
        }`}
      data-tooltip={title}
      aria-label={title}
      data-active={active ? 'true' : 'false'}
      onClick={onClick}
    >
      {children}
      {label && <span className="nav-label">{label}</span>}
    </button>
  )
}

function ServerRow({ s, isSelected, isRunning, editingId, editingName, setEditingName, onSelect, onStartEdit, onCommitEdit, onCancelEdit, onDelete, onDuplicate, onShare, ping, t }) {
  const isActive = isSelected && isRunning
  return (
    <div
      onClick={onSelect}
      className={`group rounded-lg px-3 py-2.5 cursor-pointer border transition-colors ${isSelected
        ? 'bg-violet-500/10 border-violet-500/60 shadow-[inset_3px_0_0_#795bea]'
        : 'bg-[var(--bg-panel)] border-transparent hover:bg-[var(--bg-hover)] hover:border-[var(--border)]'
        }`}
    >
      <div className="flex items-center justify-between gap-2">
        <div className="min-w-0 flex-1">
          {editingId === s.id ? (
            <input
              {...noTextAssist}
              autoFocus
              className="text-sm font-medium bg-[var(--bg-elevated)] border border-[var(--border-strong)] rounded px-1 py-0.5 w-full"
              value={editingName}
              onChange={(e) => setEditingName(e.target.value)}
              onClick={(e) => e.stopPropagation()}
              onBlur={onCommitEdit}
              onKeyDown={(e) => {
                if (e.key === 'Enter') onCommitEdit()
                if (e.key === 'Escape') onCancelEdit()
              }}
            />
          ) : (
            <div className="flex items-center gap-1.5">
              {isActive && <StatusDot state="running" />}
              <div className="text-sm font-medium truncate">{s.name}</div>
            </div>
          )}
          <div className="text-[11px] text-[var(--text-faint)] truncate mt-0.5">
            {s.protocol} · {s.address}:{s.port}
          </div>
        </div>
        {ping !== undefined && (
          <span
            className={`shrink-0 text-[11px] font-medium tabular-nums group-hover:hidden ${ping === null ? 'text-[var(--text-faint)]' : ping < 0 ? 'text-[var(--danger)]' : ping < 300 ? 'text-[var(--success)]' : 'text-amber-500'
              }`}
          >
            {ping === null ? '…' : ping < 0 ? t('timeout') : `${ping} ms`}
          </span>
        )}
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity shrink-0">
          <button
            className="server-action w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)] flex items-center justify-center"
            onClick={onDuplicate}
            data-tooltip={t('copyServer')}
            aria-label={t('copyServer')}
          >
            <Icon path={icons.copy} className="w-3.5 h-3.5" />
          </button>
          <button
            className="server-action w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)] flex items-center justify-center"
            onClick={onShare}
            data-tooltip={t('shareLink')}
            aria-label={t('shareLink')}
          >
            <Icon path={icons.share} className="w-3.5 h-3.5" />
          </button>
          <button
            className="server-action w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)] flex items-center justify-center"
            onClick={onStartEdit}
            data-tooltip={t('editServer')}
            aria-label={t('editServer')}
          >
            <Icon path={icons.pencil} className="w-3.5 h-3.5" />
          </button>
          <button
            className="server-action w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--danger)] hover:bg-[var(--danger-bg)] flex items-center justify-center"
            onClick={onDelete}
            data-tooltip={t('remove')}
            aria-label={t('remove')}
          >
            <Icon path={icons.trash} className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
    </div>
  )
}

const NETWORKS = ['tcp', 'kcp', 'ws', 'httpupgrade', 'xhttp', 'h2', 'grpc']
const XHTTP_MODES = ['auto', 'packet-up', 'stream-up', 'stream-one']
const KCP_HEADERS = ['none', 'srtp', 'utp', 'wechat-video', 'dtls', 'wireguard', 'dns']
const FINGERPRINTS = ['', 'chrome', 'firefox', 'safari', 'ios', 'android', 'edge', '360', 'qq', 'random', 'randomized']
const SS_METHODS = [
  'aes-128-gcm', 'aes-256-gcm', 'chacha20-poly1305', 'chacha20-ietf-poly1305', 'xchacha20-poly1305',
  'xchacha20-ietf-poly1305', '2022-blake3-aes-128-gcm', '2022-blake3-aes-256-gcm', '2022-blake3-chacha20-poly1305', 'none',
]
const VMESS_CIPHERS = ['auto', 'aes-128-gcm', 'chacha20-poly1305', 'none', 'zero']
const FLOWS = ['', 'xtls-rprx-vision', 'xtls-rprx-vision-udp443']

// Normalizes the transport/security keys: vmess:// links store them as
// "network"/"tls", the other link types as "type"/"security".
function editableServer(server) {
  const extra = { ...(server.extra || {}) }
  extra.type = extra.type || extra.network || 'tcp'
  extra.security = extra.security || extra.tls || 'none'
  delete extra.network
  delete extra.tls
  return { ...server, extra }
}

function Field({ label, children }) {
  return (
    <label className="block">
      <span className="block text-[11px] text-[var(--text-faint)] mb-1">{label}</span>
      {children}
    </label>
  )
}

const inputClass =
  'w-full rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)] px-2.5 py-1.5 text-xs focus:outline-none focus:border-[var(--accent)]'

function ServerEditor({ initial, onSave, onCancel, t }) {
  const [s, setS] = useState(() => editableServer(initial))
  const [err, setErr] = useState('')
  const e = s.extra
  const set = (k, v) => setS((prev) => ({ ...prev, [k]: v }))
  const setX = (k, v) => setS((prev) => ({ ...prev, extra: { ...prev.extra, [k]: v } }))
  const text = (label, value, onChange, placeholder = '') => (
    <Field label={label}>
      <input {...noTextAssist} className={inputClass} value={value ?? ''} placeholder={placeholder} onChange={(ev) => onChange(ev.target.value)} />
    </Field>
  )
  const select = (label, value, options, onChange) => (
    <Field label={label}>
      <select className={inputClass} value={value ?? ''} onChange={(ev) => onChange(ev.target.value)}>
        {options.map((o) => (
          <option key={o} value={o}>
            {o === '' ? t('none') : o}
          </option>
        ))}
      </select>
    </Field>
  )
  const checkbox = (label, checked, onChange) => (
    <label className="flex cursor-pointer items-center justify-between gap-4 rounded-lg border border-[var(--border)] bg-[var(--bg-elevated)] px-3 py-2">
      <span className="text-[11px] text-[var(--text-dim)]">{label}</span>
      <input type="checkbox" checked={checked} onChange={(ev) => onChange(ev.target.checked)} className="h-3.5 w-3.5 accent-[var(--accent)]" />
    </label>
  )

  async function save() {
    setErr('')
    // Drop empty extras so share links stay clean.
    const extra = Object.fromEntries(Object.entries(s.extra).filter(([, v]) => v !== '' && v !== undefined))
    if (extra.security === 'none') delete extra.security
    if (s.protocol === 'hysteria2' || s.protocol === 'ssh') {
      delete extra.type
      delete extra.security
    }
    try {
      await onSave({ ...s, port: Number(s.port) || 0, extra })
    } catch (ex) {
      setErr(errorText(ex))
    }
  }

  const section = (title) => <div className="text-[11px] font-semibold uppercase tracking-wide text-[var(--accent)] pt-2">{title}</div>

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={onCancel}>
      <div
        className="w-full max-w-lg max-h-[90vh] flex flex-col rounded-xl bg-[var(--bg-panel)] border border-[var(--border)]"
        onClick={(ev) => ev.stopPropagation()}
      >
        <div className="px-5 pt-4 pb-2 flex items-center justify-between">
          <h2 className="text-sm font-semibold">{initial.id ? t('editServer') : t('addManually')}</h2>
          <span className="text-[11px] uppercase text-[var(--text-faint)]">{s.protocol}</span>
        </div>
        <div className="px-5 pb-4 overflow-y-auto space-y-3">
          {section(t('basic'))}
          {text(t('name'), s.name, (v) => set('name', v))}
          <div className="grid grid-cols-3 gap-2">
            <div className="col-span-2">{text(t('address'), s.address, (v) => set('address', v), 'example.com')}</div>
            {text(t('port'), s.port, (v) => set('port', v.replace(/\D/g, '')), '443')}
          </div>
          {s.protocol === 'vmess' && (
            <>
              {text(t('uuid'), s.uuid, (v) => set('uuid', v))}
              {select(t('encryption'), e.scy || 'auto', VMESS_CIPHERS, (v) => setX('scy', v))}
            </>
          )}
          {s.protocol === 'vless' && (
            <>
              {text(t('uuid'), s.uuid, (v) => set('uuid', v))}
              {select(t('flow'), e.flow || '', FLOWS, (v) => setX('flow', v))}
              {text(t('encryption'), e.encryption, (v) => setX('encryption', v), 'none')}
            </>
          )}
          {s.protocol === 'trojan' && text(t('password'), s.password, (v) => set('password', v))}
          {s.protocol === 'ssh' && (
            <>
              {text(t('username'), e.user, (v) => setX('user', v), 'root')}
              {text(t('password'), s.password, (v) => set('password', v))}
              <Field label={t('privateKey')}>
                <textarea
                  {...noTextAssist}
                  className={inputClass + ' font-mono text-[11px] h-20'}
                  value={e.pk ?? ''}
                  placeholder="-----BEGIN OPENSSH PRIVATE KEY-----"
                  onChange={(ev) => setX('pk', ev.target.value)}
                />
              </Field>
              {e.pk && text(t('keyPassphrase'), e.pp, (v) => setX('pp', v))}
              {text(t('hostKey'), e.hk, (v) => setX('hk', v), 'SHA256:…')}
            </>
          )}
          {s.protocol === 'hysteria2' && (
            <>
              {text(t('password'), s.password, (v) => set('password', v))}
              {text(t('portHopping'), e.mport, (v) => setX('mport', v), '20000-30000')}
              {section(t('security'))}
              {text(t('sni'), e.sni, (v) => setX('sni', v))}
              {text(t('pinSHA256'), e.pinSHA256, (v) => setX('pinSHA256', v))}
              {text(t('ech'), e.ech, (v) => setX('ech', v))}
              {select(t('obfs'), e.obfs || '', ['', 'salamander'], (v) => setX('obfs', v))}
              {e.obfs === 'salamander' && text(t('obfsPassword'), e['obfs-password'], (v) => setX('obfs-password', v))}
            </>
          )}
          {s.protocol === 'shadowsocks' && (
            <>
              {select(t('method'), s.method || 'aes-256-gcm', SS_METHODS, (v) => set('method', v))}
              {text(t('password'), s.password, (v) => set('password', v))}
            </>
          )}

          {!['shadowsocks', 'hysteria2', 'ssh'].includes(s.protocol) && (
            <>
              {section(t('transport'))}
              {select(t('network'), e.type, NETWORKS, (v) => {
                setX('type', v)
                setX('headerType', '')
                setX('mode', '')
              })}
              {e.type === 'tcp' && select(t('headerType'), e.headerType || 'none', ['none', 'http'], (v) => setX('headerType', v === 'none' ? '' : v))}
              {(['ws', 'httpupgrade', 'xhttp', 'h2'].includes(e.type) || (e.type === 'tcp' && e.headerType === 'http')) && (
                <>
                  {text(t('hostHeader'), e.host, (v) => setX('host', v))}
                  {text(t('path'), e.path, (v) => setX('path', v), '/')}
                </>
              )}
              {e.type === 'xhttp' && (
                <>
                  {select(t('mode'), e.mode || 'auto', XHTTP_MODES, (v) => setX('mode', v === 'auto' ? '' : v))}
                  <Field label={t('xhttpExtra')}>
                    <textarea
                      {...noTextAssist}
                      className={inputClass + ' font-mono text-[11px] h-16'}
                      value={e.extra ?? ''}
                      placeholder='{"xPaddingBytes":"100-1000"}'
                      onChange={(ev) => setX('extra', ev.target.value)}
                    />
                  </Field>
                </>
              )}
              {e.type === 'kcp' && (
                <>
                  {select(t('headerType'), e.headerType || 'none', KCP_HEADERS, (v) => setX('headerType', v === 'none' ? '' : v))}
                  {text(t('seed'), e.seed, (v) => setX('seed', v))}
                </>
              )}
              {e.type === 'grpc' && (
                <>
                  {text(t('serviceName'), e.serviceName, (v) => setX('serviceName', v))}
                  {select(t('mode'), e.mode || 'gun', ['gun', 'multi'], (v) => setX('mode', v === 'gun' ? '' : v))}
                  {text(t('authority'), e.authority, (v) => setX('authority', v))}
                </>
              )}

              {section(t('security'))}
              {select(t('security'), e.security, ['none', 'tls', 'reality'], (v) => setX('security', v))}
              {e.security !== 'none' && (
                <>
                  {text(t('sni'), e.sni, (v) => setX('sni', v))}
                  {select(t('fingerprint'), e.fp || '', FINGERPRINTS, (v) => setX('fp', v))}
                </>
              )}
              {e.security === 'tls' && text(t('alpn'), e.alpn, (v) => setX('alpn', v), 'h2,http/1.1')}
              {e.security === 'tls' && checkbox(t('allowInsecure'), e.insecure === '1' || e.insecure === 'true', (checked) => setX('insecure', checked ? '1' : ''))}
              {e.security === 'tls' && text(t('ech'), e.ech, (v) => setX('ech', v), 'cloudflare-ech.com+https://1.1.1.1/dns-query')}
              {e.security === 'reality' && (
                <>
                  {text(t('publicKey'), e.pbk, (v) => setX('pbk', v))}
                  {text(t('shortId'), e.sid, (v) => setX('sid', v))}
                  {text(t('spiderX'), e.spx, (v) => setX('spx', v), '/')}
                </>
              )}
            </>
          )}
          {err && <p className="text-xs text-[var(--danger)]">{err}</p>}
        </div>
        <div className="px-5 py-3 border-t border-[var(--border)] flex justify-end gap-2">
          <button className="text-xs px-3 py-1.5 rounded-md hover:bg-[var(--bg-hover)]" onClick={onCancel}>
            {t('cancel')}
          </button>
          <button
            className="text-xs px-3 py-1.5 rounded-md bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-[var(--accent-text)]"
            onClick={save}
          >
            {t('save')}
          </button>
        </div>
      </div>
    </div>
  )
}

export default function App() {
  const [servers, setServers] = useState([])
  const [link, setLink] = useState('')
  const [addOpen, setAddOpen] = useState(false)
  const [status, setStatus] = useState({ state: 'stopped' })
  const [error, setError] = useState('')
  const [selectedId, setSelectedId] = useState(null)
  const [pending, setPending] = useState(false)
  const [version, setVersion] = useState('')
  const [xrayVersion, setXrayVersion] = useState('')
  const [editingId, setEditingId] = useState(null)
  const [editingName, setEditingName] = useState('')
  const [query, setQuery] = useState('')
  const [testResult, setTestResult] = useState(null)
  const [testing, setTesting] = useState(false)
  const [log, setLog] = useState('')
  const [logLoading, setLogLoading] = useState(false)
  const [logLive, setLogLive] = useState(false)
  const [aboutOpen, setAboutOpen] = useState(false)
  const [page, setPage] = useState('servers')
  const persistedSettings = useRef(null)
  const [theme, setTheme] = useState('dark')
  const [updateInfo, setUpdateInfo] = useState(null)
  const [updateDismissed, setUpdateDismissed] = useState(false)
  const [updating, setUpdating] = useState(false)
  const [updateError, setUpdateError] = useState('')
  const [checkingUpdate, setCheckingUpdate] = useState(false)
  const [updateProgress, setUpdateProgress] = useState(null)
  const [mode, setMode] = useState('proxy')
  const [proxyConfig, setProxyConfig] = useState(defaultProxyConfig)
  const [proxyAction, setProxyAction] = useState({ busy: false, message: '' })
  const [proxyStatus, setProxyStatus] = useState({ known: false, enabled: false, config: {} })
  const [outboundRules, setOutboundRules] = useState([])
  const [ruleSelectorOpen, setRuleSelectorOpen] = useState(false)
  const ruleSelectorRef = useRef(null)
  const [platform, setPlatform] = useState('')
  const [elevated, setElevated] = useState(true)
  const [killSwitch, setKillSwitch] = useState(false)
  const [lang, setLang] = useState('en')
  const [langOpen, setLangOpen] = useState(false)
  const t = useMemo(() => makeT(lang), [lang])

  function persistUISettings(patch) {
    const current = persistedSettings.current
    if (!current) return
    const next = { ...current, ui: { ...(current.ui || {}), ...patch } }
    persistedSettings.current = next
    SaveGeoSettings(next).catch(() => { })
  }

  useEffect(() => {
    document.documentElement.setAttribute('dir', getDir(lang))
    document.documentElement.setAttribute('data-lang', lang)
    persistUISettings({ lang })
  }, [lang])

  useEffect(() => {
    persistUISettings({ killSwitch })
  }, [killSwitch])

  useEffect(() => {
    if (!proxyAction.message) return undefined
    const timer = window.setTimeout(() => setProxyAction((current) => ({ ...current, message: '' })), 2400)
    return () => window.clearTimeout(timer)
  }, [proxyAction.message])

  useEffect(() => {
    if (!ruleSelectorOpen) return undefined
    const closeOnOutsideClick = (event) => {
      if (!ruleSelectorRef.current?.contains(event.target)) setRuleSelectorOpen(false)
    }
    document.addEventListener('pointerdown', closeOnOutsideClick)
    return () => document.removeEventListener('pointerdown', closeOnOutsideClick)
  }, [ruleSelectorOpen])

  useEffect(() => {
    let active = true
    const refresh = () => SystemProxyStatus()
      .then((value) => active && setProxyStatus({ known: true, enabled: Boolean(value?.enabled), config: value?.config || {} }))
      .catch(() => active && setProxyStatus((current) => ({ ...current, known: false })))
    refresh()
    const timer = window.setInterval(refresh, 2000)
    return () => {
      active = false
      window.clearInterval(timer)
    }
  }, [])

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme)
    SetWindowTheme(theme).catch(() => { })
    persistUISettings({ theme })
  }, [theme])

  useEffect(() => {
    ListProfiles()
      .then((list) => {
        setServers(list || [])
        if (list && list.length > 0) {
          setSelectedId((current) => current && list.some((server) => server.id === current) ? current : list[0].id)
        }
      })
      .catch((err) => setError(errorText(err)))
    Status().then(setStatus).catch(() => { })
    Version().then(setVersion).catch(() => { })
    XrayVersion().then(setXrayVersion).catch(() => { })
    Platform().then(setPlatform).catch(() => { })
    IsElevated().then(setElevated).catch(() => { })
    OutboundSettings().then((value) => setOutboundRules(value?.rules || [])).catch(() => { })

    const offProgress = Events.On('update:progress', (event) => setUpdateProgress(event.data))
    const offProfileSelected = Events.On('profile:selected', (event) => {
      setSelectedId(event.data)
      setPage('servers')
    })
    return () => {
      offProgress()
      offProfileSelected()
    }
  }, [])

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase()
    if (!q) return servers
    return servers.filter(
      (s) => s.name?.toLowerCase().includes(q) || s.address?.toLowerCase().includes(q) || s.protocol?.toLowerCase().includes(q),
    )
  }, [servers, query])

  const [pingMode, setPingMode] = useState('tcp')
  // id -> ms | -1 (failed) | null (running). Remembered across restarts,
  // like v2rayNG, until the next test.
  const [pings, setPings] = useState({})
  const [pinging, setPinging] = useState(false)
  const [sortByDelay, setSortByDelay] = useState(false)
  const [pingMenuOpen, setPingMenuOpen] = useState(false)
  const cancelPing = useRef(false)

  useEffect(() => {
    GeoSettings().then((settings) => {
      const ui = settings?.ui || {}
      if (ui.theme) setTheme(ui.theme)
      if (ui.lang === 'zh' || ui.lang === 'en') setLang(ui.lang)
      if (typeof ui.killSwitch === 'boolean') setKillSwitch(ui.killSwitch)
      if (ui.proxyConfig) setProxyConfig((current) => ({ ...current, ...ui.proxyConfig }))
      if (ui.pings) setPings(ui.pings)
      if (typeof ui.sortByDelay === 'boolean') setSortByDelay(ui.sortByDelay)
      if (ui.pingMode) setPingMode(ui.pingMode)
      if (ui.selectedServerId) setSelectedId(ui.selectedServerId)
      const hydrated = {
        theme: ui.theme || theme, lang: ui.lang || lang,
        killSwitch: ui.killSwitch ?? killSwitch, proxyConfig: ui.proxyConfig || proxyConfig,
        pings: ui.pings || pings, sortByDelay: ui.sortByDelay ?? sortByDelay,
        pingMode: ui.pingMode || pingMode, selectedServerId: ui.selectedServerId || selectedId,
      }
      persistedSettings.current = { ...settings, ui: hydrated }
      SaveGeoSettings(persistedSettings.current).catch(() => { })
    }).catch(() => { })
  }, [])

  useEffect(() => {
    if (selectedId) persistUISettings({ selectedServerId: selectedId })
  }, [selectedId])

  useEffect(() => {
    if (pinging) return
    persistUISettings({ pings, sortByDelay })
  }, [pings, pinging, sortByDelay])

  function choosePingMode(m) {
    setPingMode(m)
    setPings({})
    persistUISettings({ pingMode: m, pings: {} })
  }

  // Tests the given servers (everything shown, or one subscription group).
  async function runPing(list) {
    if (list.length === 0) return
    cancelPing.current = false
    setPinging(true)
    setPings((prev) => ({ ...prev, ...Object.fromEntries(list.map((s) => [s.id, null])) }))
    // Real delay starts an xray-core instance per server, so keep it gentle.
    const limit = pingMode === 'real' ? 4 : 16
    let next = 0
    async function worker() {
      while (next < list.length && !cancelPing.current) {
        const s = list[next++]
        let ms = -1
        try {
          ms = await PingServer(s.id, pingMode)
        } catch {
          ms = -1
        }
        setPings((prev) => ({ ...prev, [s.id]: ms }))
      }
    }
    await Promise.all(Array.from({ length: Math.min(limit, list.length) }, worker))
    // Servers skipped by Stop go back to "not tested".
    setPings((prev) => Object.fromEntries(Object.entries(prev).filter(([, v]) => v !== null)))
    setPinging(false)
  }

  async function handleRemoveFailed() {
    setPingMenuOpen(false)
    const failed = servers.filter((s) => pings[s.id] === -1)
    if (failed.length === 0) return
    if (!window.confirm(t('removeFailedConfirm', failed.length))) return
    for (const s of failed) {
      try {
        await DeleteProfile(s.id)
      } catch {
        // keep going
      }
    }
    const gone = new Set(failed.map((s) => s.id))
    setServers((prev) => prev.filter((s) => !gone.has(s.id)))
    if (gone.has(selectedId)) setSelectedId(null)
  }

  // Fastest first, failed last, untested in between (v2rayNG's order).
  function byDelay(list) {
    if (!sortByDelay) return list
    const rank = (s) => {
      const v = pings[s.id]
      if (v === undefined || v === null) return 1e9
      return v < 0 ? 2e9 : v
    }
    return [...list].sort((a, b) => rank(a) - rank(b))
  }

  // Servers imported from a subscription URL all share the same
  // extra.subGroup id -- fold those into one collapsible row instead of
  // flooding the list (a subscription can carry hundreds of servers).
  const { standalone, groups } = useMemo(() => {
    const groupMap = new Map()
    const standalone = []
    for (const s of filtered) {
      const groupId = s.extra?.subGroup
      if (!groupId) {
        standalone.push(s)
        continue
      }
      if (!groupMap.has(groupId)) {
        let notes = []
        try {
          notes = s.extra?.subNotes ? JSON.parse(s.extra.subNotes) : []
        } catch {
          notes = []
        }
        let usage = null
        try {
          usage = s.extra?.subUsage ? JSON.parse(s.extra.subUsage) : null
        } catch {
          usage = null
        }
        groupMap.set(groupId, {
          id: groupId,
          name: s.extra?.subGroupName || 'Subscription',
          url: s.extra?.subURL || '',
          updatedAt: Number(s.extra?.subUpdatedAt || 0),
          updateHours: Number(s.extra?.subUpdateHours || 0),
          servers: [],
          notes,
          usage,
        })
      }
      groupMap.get(groupId).servers.push(s)
    }
    for (const g of groupMap.values()) g.servers = byDelay(g.servers)
    return { standalone: byDelay(standalone), groups: [...groupMap.values()] }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filtered, pings, sortByDelay])

  const autoSynced = useRef(false)
  useEffect(() => {
    if (autoSynced.current || groups.length === 0) return
    autoSynced.current = true
    const now = Date.now() / 1000
    for (const g of groups) {
      if (g.updateHours > 0 && now - g.updatedAt > g.updateHours * 3600) {
        RefreshSubscription(g.id)
          .then((fresh) => setServers((prev) => [...prev.filter((s) => s.extra?.subGroup !== g.id), ...fresh]))
          .catch(() => { })
      }
    }
  }, [groups])

  const [expandedGroups, setExpandedGroups] = useState(() => new Set())
  const [refreshingGroup, setRefreshingGroup] = useState(null)
  const [shareMenuGroup, setShareMenuGroup] = useState(null)
  const [editGroup, setEditGroup] = useState(null) // { id, name, url }
  const [editServer, setEditServer] = useState(null) // server being edited / added

  async function handleSaveServer(server) {
    const saved = await SaveProfile(server)
    setServers((prev) => (prev.some((x) => x.id === saved.id) ? prev.map((x) => (x.id === saved.id ? saved : x)) : [...prev, saved]))
    setSelectedId(saved.id)
    setEditServer(null)
  }

  async function handleSaveOutboundRule(rule) {
    await SaveOutboundRule(rule)
    setOutboundRules((current) => current.some((item) => item.id === rule.id) ? current.map((item) => item.id === rule.id ? rule : item) : [...current, rule])
  }

  async function handleDeleteOutboundRule(id) {
    await DeleteOutboundRule(id)
    setOutboundRules((current) => current.filter((item) => item.id !== id))
    setServers((current) => current.map((server) => ({ ...server, outboundRuleIds: (server.outboundRuleIds || []).filter((ruleID) => ruleID !== id) })))
  }

  async function toggleServerOutboundRule(ruleID) {
    if (!selected) return
    const current = selected.outboundRuleIds || []
    const outboundRuleIds = current.includes(ruleID) ? current.filter((id) => id !== ruleID) : [...current, ruleID]
    try {
      const saved = await SaveProfile({ ...selected, outboundRuleIds })
      setServers((servers) => servers.map((server) => server.id === saved.id ? saved : server))
    } catch (err) {
      setError(errorText(err))
    }
  }
  const [notice, setNotice] = useState('')
  const noticeTimer = useRef(null)

  function flash(msg) {
    setNotice(msg)
    clearTimeout(noticeTimer.current)
    noticeTimer.current = setTimeout(() => setNotice(''), 2000)
  }

  async function handleShareServer(id, e) {
    e.stopPropagation()
    setError('')
    try {
      await copyText(await ShareLink(id))
      flash(t('linkCopied'))
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleShareGroup(g, what) {
    setShareMenuGroup(null)
    setError('')
    try {
      await copyText(what === 'url' ? g.url : await ShareSubscription(g.id))
      flash(t('linkCopied'))
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleSaveGroup() {
    const { id, name, url } = editGroup
    setError('')
    try {
      await EditSubscription(id, name, url)
      setServers((prev) =>
        prev.map((s) =>
          s.extra?.subGroup === id ? { ...s, extra: { ...s.extra, subGroupName: name.trim(), subURL: url.trim() } } : s,
        ),
      )
      setEditGroup(null)
    } catch (err) {
      setError(errorText(err))
    }
  }
  const searching = query.trim().length > 0
  function toggleGroup(id) {
    setExpandedGroups((prev) => {
      const next = new Set(prev)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  async function handleSyncGroup(groupId, e) {
    e.stopPropagation()
    setRefreshingGroup(groupId)
    setError('')
    try {
      const fresh = await RefreshSubscription(groupId)
      setServers((prev) => [...prev.filter((s) => s.extra?.subGroup !== groupId), ...fresh])
      // Refreshed servers get new IDs; keep the same server selected.
      if (selected?.extra?.subGroup === groupId) {
        const match = fresh.find((s) => s.address === selected.address && s.port === selected.port && s.name === selected.name)
          || fresh.find((s) => s.address === selected.address && s.port === selected.port)
        setSelectedId(match ? match.id : null)
      }
    } catch (err) {
      setError(errorText(err))
    } finally {
      setRefreshingGroup(null)
    }
  }

  async function handleDeleteGroup(groupId, e) {
    e.stopPropagation()
    setError('')
    try {
      await DeleteSubscriptionGroup(groupId)
      setServers((prev) => prev.filter((s) => s.extra?.subGroup !== groupId))
      if (selected?.extra?.subGroup === groupId) setSelectedId(null)
    } catch (err) {
      setError(errorText(err))
    }
  }

  function usageInfo(usage) {
    if (!usage || (!usage.totalBytes && !usage.expireUnix && !usage.uploadBytes && !usage.downloadBytes)) return null
    const usedGB = (usage.uploadBytes + usage.downloadBytes) / 1e9
    const totalGB = usage.totalBytes > 0 ? usage.totalBytes / 1e9 : null
    return {
      usedGB: usedGB.toFixed(1),
      totalGB: totalGB !== null ? totalGB.toFixed(1) : null,
      pct: totalGB ? Math.min(100, (usedGB / totalGB) * 100) : null,
      expiryDate: usage.expireUnix > 0 ? new Date(usage.expireUnix * 1000) : null,
    }
  }

  const selected = servers.find((s) => s.id === selectedId) || null
  const isRunning = status.state === 'running'
  const isBusy = pending || status.state === 'starting'
  const needsElevation = (mode === 'tun' || killSwitch) && !elevated

  // The tray menu can disconnect while the window is hidden; poll so the
  // UI never shows a stale "Connected".
  useEffect(() => {
    if (pending) return
    const id = setInterval(() => {
      Status().then(setStatus).catch(() => { })
    }, 2000)
    return () => clearInterval(id)
  }, [pending])

  const [trafficOpen, setTrafficOpen] = useState(false)
  const [traffic, setTraffic] = useState({ uplink: 0, downlink: 0 })
  const [speed, setSpeed] = useState({ up: 0, down: 0 })
  const lastTraffic = useRef(null)

  useEffect(() => {
    if (!isRunning) {
      lastTraffic.current = null
      setTraffic({ uplink: 0, downlink: 0 })
      setSpeed({ up: 0, down: 0 })
      return
    }
    const poll = () => {
      Traffic()
        .then((t) => {
          const prev = lastTraffic.current
          if (prev) {
            const elapsed = (Date.now() - prev.at) / 1000
            setSpeed({
              up: elapsed > 0 ? Math.max(0, (t.uplink - prev.uplink) / elapsed) : 0,
              down: elapsed > 0 ? Math.max(0, (t.downlink - prev.downlink) / elapsed) : 0,
            })
          }
          lastTraffic.current = { uplink: t.uplink, downlink: t.downlink, at: Date.now() }
          setTraffic(t)
        })
        .catch(() => { })
    }
    poll()
    const id = setInterval(poll, 1000)
    return () => clearInterval(id)
  }, [isRunning])

  function formatBytes(n) {
    if (!n) return '0B'
    const units = ['B', 'KB', 'MB', 'GB', 'TB']
    let i = 0
    while (n >= 1024 && i < units.length - 1) {
      n /= 1024
      i++
    }
    return `${n < 10 && i > 0 ? n.toFixed(1) : Math.round(n)}${units[i]}`
  }
  function formatSpeed(n) {
    return `${formatBytes(n)}/s`
  }

  async function handleAddLink() {
    const value = link.trim()
    if (!value) return
    setError('')
    try {
      if (/^https?:\/\//i.test(value)) {
        const added = await AddSubscription(value)
        setServers((prev) => [...prev, ...added])
        if (added.length > 0) setSelectedId(added[added.length - 1].id)
      } else {
        const server = await AddProfileFromLink(value)
        setServers((prev) => [...prev, server])
        setSelectedId(server.id)
      }
      setLink('')
      setAddOpen(false)
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleToggle() {
    setError('')
    setTestResult(null)
    if (isRunning) {
      setPending(true)
      try {
        await Disconnect()
        setStatus(await Status())
      } catch (err) {
        setError(errorText(err))
      } finally {
        setPending(false)
      }
      return
    }

    if (!selected) {
      setError(t('addServerFirst'))
      return
    }
    setPending(true)
    try {
      await Connect(selected.id, mode, killSwitch)
      setStatus(await Status())
      handleTest()
    } catch (err) {
      setError(errorText(err))
      setStatus(await Status().catch(() => ({ state: 'stopped' })))
    } finally {
      setPending(false)
    }
  }

  async function handleRestartElevated() {
    setError('')
    try {
      await RestartElevated()
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleDelete(id, e) {
    e.stopPropagation()
    setError('')
    try {
      await DeleteProfile(id)
      setServers((prev) => prev.filter((s) => s.id !== id))
      if (selectedId === id) setSelectedId(null)
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleDuplicateServer(server, e) {
    e.stopPropagation()
    setError('')
    const extra = { ...(server.extra || {}) }
    for (const key of ['subGroup', 'subGroupName', 'subURL', 'subUsage', 'subNotes', 'subUpdatedAt', 'subUpdateHours']) delete extra[key]
    try {
      const duplicate = await SaveProfile({
        ...server,
        id: '',
        name: `${server.name} copy`,
        extra,
        outboundRuleIds: [...(server.outboundRuleIds || [])],
      })
      setServers((prev) => [...prev, duplicate])
      setSelectedId(duplicate.id)
    } catch (err) {
      setError(errorText(err))
    }
  }

  function startEditing(server, e) {
    e.stopPropagation()
    setEditingId(server.id)
    setEditingName(server.name)
  }

  async function commitEditing(id) {
    const name = editingName.trim()
    setEditingId(null)
    if (!name) return
    setError('')
    try {
      const updated = await RenameProfile(id, name)
      setServers((prev) => prev.map((s) => (s.id === id ? updated : s)))
    } catch (err) {
      setError(errorText(err))
    }
  }

  async function handleTest() {
    setTesting(true)
    setTestResult(null)
    try {
      const result = await TestConnection()
      setTestResult({ ok: true, ...result })
    } catch (err) {
      setTestResult({ ok: false, text: errorText(err) })
    } finally {
      setTesting(false)
    }
  }

  async function handleShowLog() {
    setPage('logs')
    setLogLoading(true)
    try {
      setLog(await RecentLog())
    } catch (err) {
      setLog(errorText(err))
    } finally {
      setLogLoading(false)
    }
  }

  useEffect(() => {
    if (page !== 'logs' || !logLive) return undefined

    let cancelled = false
    let refreshing = false
    const refresh = async () => {
      if (refreshing) return
      refreshing = true
      try {
        const next = await RecentLog()
        if (!cancelled) setLog(next)
      } catch (err) {
        if (!cancelled) setLog(errorText(err))
      } finally {
        refreshing = false
      }
    }

    refresh()
    const timer = window.setInterval(refresh, 1000)
    return () => {
      cancelled = true
      window.clearInterval(timer)
    }
  }, [page, logLive])

  async function handleApplyProxy() {
    setProxyAction({ busy: true, message: '' })
    try {
      const normalizedConfig = normalizeProxyPorts(proxyConfig, t('invalidProxyPort'))
      if (normalizedConfig.socksPort === normalizedConfig.httpPort || normalizedConfig.socksPort === normalizedConfig.httpsPort) {
        throw new Error(t('proxyPortConflict'))
      }
      await SetSystemProxy(normalizedConfig)
      const current = await SystemProxyStatus().catch(() => ({ enabled: true, config: normalizedConfig }))
      setProxyConfig(normalizedConfig)
      persistUISettings({ proxyConfig: normalizedConfig })
      setProxyStatus({ known: true, enabled: Boolean(current?.enabled), config: current?.config || normalizedConfig })
      setProxyAction({ busy: false, message: lang === 'zh' ? '系统代理已设置' : 'System proxy applied' })
    } catch (err) {
      setProxyAction({ busy: false, message: errorText(err) })
    }
  }

  async function handleSaveProxyConfig(config) {
    const normalizedConfig = normalizeProxyPorts(config, t('invalidProxyPort'))
    if (normalizedConfig.socksPort === normalizedConfig.httpPort || normalizedConfig.socksPort === normalizedConfig.httpsPort) {
      throw new Error(t('proxyPortConflict'))
    }
    await SaveSystemProxyConfig(normalizedConfig)
    setProxyConfig(normalizedConfig)
    persistUISettings({ proxyConfig: normalizedConfig })
  }

  async function handleClearProxy() {
    setProxyAction({ busy: true, message: '' })
    try {
      await ClearSystemProxy()
      const current = await SystemProxyStatus().catch(() => ({ enabled: false, config: {} }))
      setProxyStatus({ known: true, enabled: Boolean(current?.enabled), config: current?.config || {} })
      setProxyAction({ busy: false, message: lang === 'zh' ? '系统代理已取消' : 'System proxy cleared' })
    } catch (err) {
      setProxyAction({ busy: false, message: errorText(err) })
    }
  }

  async function handleCopyTerminalProxy() {
    const http = `http://${proxyConfig.httpHost}:${proxyConfig.httpPort}`
    const https = `http://${proxyConfig.httpsHost}:${proxyConfig.httpsPort}`
    const socks = `socks5://${proxyConfig.socksHost}:${proxyConfig.socksPort}`
    const command = `export http_proxy=${http} https_proxy=${https} all_proxy=${socks} HTTP_PROXY=${http} HTTPS_PROXY=${https} ALL_PROXY=${socks}`
    try {
      await copyText(command)
      setProxyAction({ busy: false, message: lang === 'zh' ? '终端代理命令已复制' : 'Terminal proxy command copied' })
    } catch (err) {
      setProxyAction({ busy: false, message: errorText(err) })
    }
  }

  async function handleCheckUpdate() {
    setCheckingUpdate(true)
    setUpdateError('')
    try {
      const info = await CheckForUpdate()
      setUpdateInfo(info)
      setUpdateDismissed(false)
    } catch (err) {
      setUpdateError(errorText(err))
    } finally {
      setCheckingUpdate(false)
    }
  }

  async function handleUpdate() {
    setUpdating(true)
    setUpdateError('')
    setUpdateProgress(null)
    try {
      // ApplyUpdate only returns on failure -- on success the process
      // exits and relaunches before this promise would ever resolve.
      await ApplyUpdate()
    } catch (err) {
      setUpdateError(errorText(err))
      setUpdating(false)
      setUpdateProgress(null)
    }
  }

  const showUpdateBanner = updateInfo?.available && !updateDismissed
  const progressPct =
    updateProgress && updateProgress.total > 0 ? Math.min(100, Math.round((updateProgress.downloaded / updateProgress.total) * 100)) : null

  return (
    <div className="h-screen flex flex-col bg-[var(--bg)] text-[var(--text)] overflow-hidden">
      {showUpdateBanner && (
        <div className="flex flex-col shrink-0">
          <div className="flex items-center gap-3 px-4 py-2 bg-[var(--accent)] text-[var(--accent-text)] text-sm">
            <Icon path={icons.download} className="w-4 h-4 shrink-0" />
            <span className="flex-1">
              {updating
                ? progressPct !== null
                  ? t('downloadingUpdatePct', progressPct)
                  : t('downloadingUpdate')
                : t('updateAvailableBanner', updateInfo.latest, updateInfo.current || version)}
            </span>
            {!updating && (
              <button
                onClick={handleUpdate}
                className="rounded-md bg-white/20 hover:bg-white/30 px-3 py-1 text-xs font-medium transition-colors"
              >
                {t('updateNow')}
              </button>
            )}
            {!updating && (
              <button onClick={() => setUpdateDismissed(true)} className="text-white/70 hover:text-white">
                <Icon path={icons.x} className="w-4 h-4" />
              </button>
            )}
          </div>
          {updating && (
            <div className="h-1 bg-black/20">
              <div
                className="h-full bg-white/80 transition-all duration-150"
                style={{ width: progressPct !== null ? `${progressPct}%` : '30%' }}
              />
            </div>
          )}
        </div>
      )}
      {updateError && (
        <div className="px-4 py-1.5 bg-[var(--danger-bg)] text-[var(--danger)] text-xs shrink-0">{t('updateFailed', updateError)}</div>
      )}

      <div className="flex-1 flex overflow-hidden">
        {/* Icon rail */}
        <aside className="app-sidebar w-[168px] flex flex-col py-6 px-2 gap-1 bg-[var(--bg-panel)] border-r border-[var(--border)] shrink-0 transition-[width]">
          <div className="brand-area flex items-center gap-3 px-2 mb-7"><img src={logo} alt="Krab" className="brand-logo w-10 h-10 min-w-10 shrink-0 aspect-square rounded-full object-cover ring-1 ring-white/15 shadow-[0_4px_18px_rgba(0,0,0,.3)]" /><div className="brand-copy"><b className="block text-sm tracking-[.22em]">KRAB</b><small className="block text-[8px] tracking-[.16em] text-[var(--text-faint)] mt-1">XRAY PANEL</small></div></div>
          <IconButton active={page === 'servers'} label={t('servers')} title={t('servers')} onClick={() => setPage('servers')}>
            <Icon path={icons.globe} className="w-5 h-5" />
          </IconButton>
          <IconButton active={page === 'outbound'} label={t('outboundRules')} title={t('outboundRules')} onClick={() => setPage('outbound')}>
            <Icon path={icons.outbound} className="w-5 h-5" />
          </IconButton>
          <IconButton active={page === 'logs'} label={lang === 'zh' ? '日志' : 'Logs'} title={lang === 'zh' ? '日志' : 'Logs'} onClick={handleShowLog}>
            <Icon path={icons.terminal} className="w-5 h-5" />
          </IconButton>
          <IconButton active={page === 'stats'} label={t('stats')} title={t('stats')} onClick={() => setPage('stats')}>
            <Icon path={icons.chart} className="w-5 h-5" />
          </IconButton>
          <div className="relative w-full">
            <IconButton label={t('language')} title={t('language')} onClick={() => setLangOpen((v) => !v)}>
              <Icon path={icons.language} className="w-5 h-5" />
            </IconButton>
            {langOpen && (
              <>
                <div className="fixed inset-0 z-40" onClick={() => setLangOpen(false)} />
                <div className="language-menu absolute left-[150px] bottom-0 z-50 w-[210px] rounded-xl border border-[var(--border)] bg-[var(--bg-panel)] p-2 shadow-[0_18px_50px_rgba(0,0,0,.22)]" role="menu" aria-label={t('language')}>
                  <div className="space-y-1">
                    {LANGUAGES.map((l) => (
                      <button
                        key={l.code}
                        lang={l.code}
                        role="menuitemradio"
                        aria-checked={lang === l.code}
                        onClick={() => {
                          setLang(l.code)
                          setLangOpen(false)
                        }}
                        className={`group flex w-full items-center gap-2.5 rounded-lg px-3 py-2 text-left transition-colors ${lang === l.code
                          ? 'bg-[var(--accent)]/10 text-[var(--text)]'
                          : 'text-[var(--text-dim)] hover:bg-[var(--bg-hover)] hover:text-[var(--text)]'
                          }`}
                      >
                        <span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-[9px] font-semibold tracking-wide ${lang === l.code ? 'bg-[var(--accent)] text-white' : 'bg-[var(--bg-elevated)] text-[var(--text-dim)]'}`}>
                          {l.code === 'zh' ? '中' : 'EN'}
                        </span>
                        <span className="min-w-0 flex-1 text-[11px] font-medium">{l.label}</span>
                        <span className={`flex h-4 w-4 items-center justify-center ${lang === l.code ? 'text-[var(--accent)]' : 'text-transparent'}`}>
                          <Icon path="m6 12 4 4 8-8" className="h-3 w-3" />
                        </span>
                      </button>
                    ))}
                  </div>
                </div>
              </>
            )}
          </div>
          <IconButton label={theme === 'dark' ? t('switchToLight') : t('switchToDark')} title={theme === 'dark' ? t('switchToLight') : t('switchToDark')} onClick={() => setTheme((th) => (th === 'dark' ? 'light' : 'dark'))}>
            <Icon path={theme === 'dark' ? icons.sun : icons.moon} className="w-5 h-5" />
          </IconButton>
          <div className="flex-1" />
          <div className="core-card mx-1 mb-3 rounded-lg border border-[var(--border)] bg-[var(--bg-elevated)] p-3"><div className="flex items-center gap-2 text-[9px]"><i className={`w-1.5 h-1.5 rounded-full ${isRunning ? 'bg-emerald-400 shadow-[0_0_8px_#43d39d]' : 'bg-slate-600'}`} />xray-core <span className="ml-auto text-[var(--text-faint)]">{xrayVersion || '—'}</span></div><div className="h-[3px] rounded-full bg-[var(--border)] mt-3 overflow-hidden"><div className={`h-full bg-gradient-to-r from-[#7657ea] to-[#3dccd8] transition-all ${isRunning ? 'w-full' : 'w-1/3'}`} /></div></div>
          <IconButton active={page === 'proxy-settings'} label={lang === 'zh' ? '系统配置' : 'System settings'} title={lang === 'zh' ? '系统配置' : 'System settings'} onClick={() => setPage('proxy-settings')}>
            <Icon path={icons.settings} className="w-5 h-5" />
          </IconButton>
        </aside>

        {page === 'logs' ? (
          <LogsView lang={lang} log={log} loading={logLoading} live={logLive} onRefresh={handleShowLog} onToggleLive={() => setLogLive((value) => !value)} />
        ) : page === 'stats' ? (
          <StatsView t={t} loadTraffic={Traffic} />
        ) : page === 'outbound' ? (
          <OutboundSettingsView lang={lang} t={t} loadSettings={OutboundSettings} saveRule={handleSaveOutboundRule} deleteRule={handleDeleteOutboundRule} />
        ) : page === 'proxy-settings' ? (
          <ProxySettingsView lang={lang} t={t} version={version} onOpenAbout={() => setAboutOpen(true)} config={proxyConfig} onConfigChange={setProxyConfig} saveProxyConfig={handleSaveProxyConfig} loadGeoSettings={GeoSettings} saveGeoSettings={SaveGeoSettings} updateGeoData={UpdateGeoData} loadAutoStart={AutoStartEnabled} setAutoStart={SetAutoStart} />
        ) : <>
          {/* Server list */}
          <section className="server-pane w-[300px] border-r border-[var(--border)] flex flex-col shrink-0">
            <div className="p-4 border-b border-[var(--border)]">
              <h1 className="text-lg font-semibold mb-3">Krab</h1>
              <div className="flex items-center gap-2">
                <div className="relative flex-1">
                  <Icon path={icons.search} className="w-4 h-4 absolute left-2.5 top-1/2 -translate-y-1/2 text-[var(--text-faint)]" />
                  <input
                    {...noTextAssist}
                    className="w-full rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)] pl-8 pr-2 py-2 text-sm placeholder:text-[var(--text-faint)] focus:outline-none focus:border-[var(--accent)]"
                    placeholder={t('searchServers')}
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                  />
                </div>
                <button
                  className="w-9 h-9 shrink-0 rounded-lg bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-[var(--accent-text)] flex items-center justify-center transition-colors"
                  title={t('addServer')}
                  onClick={() => setAddOpen((v) => !v)}
                >
                  <Icon path={icons.plus} className="w-4 h-4" />
                </button>
              </div>

              <div className="flex items-center gap-2 mt-3">
                <div className="flex flex-1 rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)] p-0.5 text-[11px]">
                  {[
                    ['tcp', 'TCP'],
                    ['http', 'HTTP'],
                    ['real', t('realDelay')],
                  ].map(([m, label]) => (
                    <button
                      key={m}
                      onClick={() => choosePingMode(m)}
                      disabled={pinging}
                      className={`flex-1 whitespace-nowrap rounded-md px-1 py-1 transition-colors ${pingMode === m ? 'bg-[var(--accent)] text-[var(--accent-text)]' : 'text-[var(--text-dim)] hover:text-[var(--text)]'
                        }`}
                    >
                      {label}
                    </button>
                  ))}
                </div>
                {pinging ? (
                  <button
                    onClick={() => (cancelPing.current = true)}
                    className="shrink-0 rounded-lg border border-[var(--danger-border)] text-[var(--danger)] hover:bg-[var(--danger-bg)] px-2.5 py-1 text-[11px]"
                  >
                    {t('stop')}
                  </button>
                ) : (
                  <button
                    onClick={() => runPing(filtered)}
                    disabled={filtered.length === 0}
                    title={t('pingAll')}
                    className="shrink-0 rounded-lg border border-[var(--border)] hover:bg-[var(--bg-hover)] px-2.5 py-1 text-[11px] text-[var(--text-dim)] disabled:opacity-50"
                  >
                    {t('pingAll')}
                  </button>
                )}
                <div className="relative shrink-0">
                  <button
                    onClick={() => setPingMenuOpen((v) => !v)}
                    className="rounded-lg border border-[var(--border)] hover:bg-[var(--bg-hover)] w-7 h-[26px] flex items-center justify-center text-[var(--text-dim)]"
                    title={t('more')}
                  >
                    ⋮
                  </button>
                  {pingMenuOpen && (
                    <>
                      <div className="fixed inset-0 z-40" onClick={() => setPingMenuOpen(false)} />
                      <div className="absolute right-0 top-8 z-50 w-52 rounded-lg border border-[var(--border)] bg-[var(--bg-panel)] shadow-lg py-1 text-xs">
                        <button
                          className="w-full text-left px-3 py-1.5 hover:bg-[var(--bg-hover)] flex items-center gap-2"
                          onClick={() => {
                            setSortByDelay((v) => !v)
                            setPingMenuOpen(false)
                          }}
                        >
                          <span className="w-3">{sortByDelay ? '✓' : ''}</span>
                          {t('sortByDelay')}
                        </button>
                        <button
                          className="w-full text-left px-3 py-1.5 hover:bg-[var(--bg-hover)] flex items-center gap-2 disabled:opacity-40"
                          disabled={pinging || !servers.some((s) => pings[s.id] === -1)}
                          onClick={handleRemoveFailed}
                        >
                          <span className="w-3" />
                          {t('removeFailed')}
                        </button>
                        <button
                          className="w-full text-left px-3 py-1.5 hover:bg-[var(--bg-hover)] flex items-center gap-2"
                          onClick={() => {
                            setPings({})
                            setPingMenuOpen(false)
                          }}
                        >
                          <span className="w-3" />
                          {t('clearResults')}
                        </button>
                      </div>
                    </>
                  )}
                </div>
              </div>

              {addOpen && (
                <div className="flex gap-2 mt-3">
                  <input
                    {...noTextAssist}
                    autoFocus
                    className="flex-1 rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)] px-3 py-2 text-xs placeholder:text-[var(--text-faint)] focus:outline-none focus:border-[var(--accent)]"
                    placeholder={t('addLinkPlaceholder')}
                    value={link}
                    onChange={(e) => setLink(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleAddLink()}
                  />
                  <button
                    className="rounded-lg bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-[var(--accent-text)] px-3 text-xs font-medium transition-colors"
                    onClick={handleAddLink}
                  >
                    {t('add')}
                  </button>
                </div>
              )}
              {addOpen && (
                <div className="flex flex-wrap items-center gap-1.5 mt-2 text-[11px] text-[var(--text-faint)]">
                  <span className="w-full">{t('addManually')}:</span>
                  {['vless', 'vmess', 'trojan', 'shadowsocks', 'hysteria2', 'ssh'].map((proto) => (
                    <button
                      key={proto}
                      className="rounded border border-[var(--border)] px-1.5 py-0.5 hover:bg-[var(--bg-hover)] text-[var(--text-dim)]"
                      onClick={() => setEditServer({ id: '', name: '', protocol: proto, address: '', port: proto === 'ssh' ? 22 : 443, extra: {} })}
                    >
                      {proto === 'shadowsocks' ? 'ss' : proto}
                    </button>
                  ))}
                </div>
              )}
            </div>

            <div className="flex-1 overflow-y-auto p-2 space-y-1">
              {filtered.length === 0 && (
                <div className="text-center text-[var(--text-faint)] text-xs mt-10 px-4">
                  {servers.length === 0 ? t('noServersYet') : t('noMatches')}
                </div>
              )}
              {standalone.map((s) => (
                <ServerRow
                  key={s.id}
                  s={s}
                  isSelected={s.id === selectedId}
                  isRunning={isRunning}
                  editingId={editingId}
                  editingName={editingName}
                  setEditingName={setEditingName}
                  onSelect={() => setSelectedId(s.id)}
                  onStartEdit={(e) => {
                    e.stopPropagation()
                    setEditServer(s)
                  }}
                  onCommitEdit={() => commitEditing(s.id)}
                  onCancelEdit={() => setEditingId(null)}
                  onDelete={(e) => handleDelete(s.id, e)}
                  onDuplicate={(e) => handleDuplicateServer(s, e)}
                  onShare={(e) => handleShareServer(s.id, e)}
                  ping={pings[s.id]}
                  t={t}
                />
              ))}
              {groups.map((g) => {
                const isOpen = searching || expandedGroups.has(g.id)
                const activeInGroup = g.servers.some((s) => s.id === selectedId)
                const info = usageInfo(g.usage)
                return (
                  <div
                    key={g.id}
                    className={`rounded-lg border overflow-hidden transition-colors ${activeInGroup ? 'border-[var(--accent)]/50' : 'border-transparent hover:border-[var(--border)]'
                      }`}
                  >
                    <div
                      onClick={() => toggleGroup(g.id)}
                      className={`group flex items-center gap-2 px-3 py-2.5 cursor-pointer transition-colors ${activeInGroup ? 'bg-[var(--accent)]/10' : 'bg-[var(--bg-panel)] hover:bg-[var(--bg-hover)]'
                        }`}
                    >
                      <Icon
                        path="m9 18 6-6-6-6"
                        className={`w-3.5 h-3.5 shrink-0 text-[var(--text-faint)] transition-transform ${isOpen ? 'rotate-90' : ''}`}
                      />
                      <div className="min-w-0 flex-1">
                        <div className="text-sm font-medium truncate">{g.name}</div>
                        <div className="text-[11px] text-[var(--text-faint)] truncate mt-0.5">
                          {g.servers.length} servers
                          {!info && g.notes.length > 0 && <> · {g.notes.join(' · ')}</>}
                        </div>
                      </div>
                      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity shrink-0" onClick={(e) => e.stopPropagation()}>
                        <button
                          className="w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)] flex items-center justify-center disabled:opacity-40"
                          onClick={() => runPing(g.servers)}
                          disabled={pinging}
                          title={t('pingGroup')}
                        >
                          <Icon path={icons.gauge} className="w-3.5 h-3.5" />
                        </button>
                        <button
                          className="w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)] flex items-center justify-center"
                          onClick={(e) => handleSyncGroup(g.id, e)}
                          disabled={refreshingGroup === g.id}
                          title={t('syncSubscription')}
                        >
                          <Icon
                            path="M4 4v5h5M20 20v-5h-5M4.6 15a8 8 0 0 0 14.8 2.5M19.4 9A8 8 0 0 0 4.6 6.5"
                            className={`w-3.5 h-3.5 ${refreshingGroup === g.id ? 'animate-spin' : ''}`}
                          />
                        </button>
                        <div className="relative">
                          <button
                            className="w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)] flex items-center justify-center"
                            onClick={(e) => {
                              const r = e.currentTarget.getBoundingClientRect()
                              setShareMenuGroup((cur) => (cur?.id === g.id ? null : { id: g.id, x: r.right, y: r.bottom }))
                            }}
                            title={t('share')}
                          >
                            <Icon path={icons.share} className="w-3.5 h-3.5" />
                          </button>
                          {shareMenuGroup?.id === g.id && (
                            <>
                              <div className="fixed inset-0 z-40" onClick={() => setShareMenuGroup(null)} />
                              <div
                                style={{ left: shareMenuGroup.x - 192, top: shareMenuGroup.y + 4 }}
                                className="fixed z-50 w-48 rounded-lg border border-[var(--border)] bg-[var(--bg-panel)] shadow-lg py-1 text-xs">
                                <button className="w-full text-left px-3 py-1.5 hover:bg-[var(--bg-hover)]" onClick={() => handleShareGroup(g, 'url')}>
                                  {t('copySubscriptionUrl')}
                                </button>
                                <button className="w-full text-left px-3 py-1.5 hover:bg-[var(--bg-hover)]" onClick={() => handleShareGroup(g, 'links')}>
                                  {t('copyAllServerLinks')}
                                </button>
                              </div>
                            </>
                          )}
                        </div>
                        <button
                          className="w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--text)] hover:bg-[var(--bg-hover)] flex items-center justify-center"
                          onClick={() => setEditGroup({ id: g.id, name: g.name, url: g.url })}
                          title={t('edit')}
                        >
                          <Icon path={icons.pencil} className="w-3.5 h-3.5" />
                        </button>
                        <button
                          className="w-6 h-6 rounded text-[var(--text-faint)] hover:text-[var(--danger)] hover:bg-[var(--danger-bg)] flex items-center justify-center"
                          onClick={(e) => handleDeleteGroup(g.id, e)}
                          title={t('remove')}
                        >
                          <Icon path={icons.trash} className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    </div>
                    {info && (
                      <div className="flex items-center gap-2 px-3 py-2 bg-[var(--bg-elevated)] border-t border-[var(--border)]">
                        {info.pct !== null ? (
                          <>
                            <div className="flex-1 h-1.5 rounded-full bg-[var(--border-strong)] overflow-hidden">
                              <div
                                className={`h-full rounded-full ${info.pct >= 90 ? 'bg-[var(--danger)]' : 'bg-[var(--accent)]'}`}
                                style={{ width: `${info.pct}%` }}
                              />
                            </div>
                            <span className="shrink-0 text-[11px] text-[var(--text-dim)] font-medium">
                              {info.usedGB}/{info.totalGB} GB
                            </span>
                          </>
                        ) : (
                          <span className="flex-1 text-[11px] text-[var(--text-dim)]">{t('gbUsedUnlimited', info.usedGB)}</span>
                        )}
                        {info.expiryDate && (
                          <span className="shrink-0 text-[11px] text-[var(--text-faint)]">
                            {t('expires')} {info.expiryDate.toLocaleDateString()}
                          </span>
                        )}
                      </div>
                    )}
                    {isOpen && (
                      <div className="pl-3 space-y-1 border-l border-[var(--border)] ml-4">
                        {g.servers.map((s) => (
                          <ServerRow
                            key={s.id}
                            s={s}
                            isSelected={s.id === selectedId}
                            isRunning={isRunning}
                            editingId={editingId}
                            editingName={editingName}
                            setEditingName={setEditingName}
                            onSelect={() => setSelectedId(s.id)}
                            onStartEdit={(e) => {
                              e.stopPropagation()
                              setEditServer(s)
                            }}
                            onCommitEdit={() => commitEditing(s.id)}
                            onCancelEdit={() => setEditingId(null)}
                            onDelete={(e) => handleDelete(s.id, e)}
                            onDuplicate={(e) => handleDuplicateServer(s, e)}
                            onShare={(e) => handleShareServer(s.id, e)}
                            ping={pings[s.id]}
                            t={t}
                          />
                        ))}
                      </div>
                    )}
                  </div>
                )
              })}
            </div>
          </section>

          {/* Connect panel */}
          <main className="connect-pane flex-1 flex flex-col items-center justify-center gap-6 px-8 pb-8 pt-28 relative overflow-y-auto">
            <div className="absolute top-8 left-1/2 z-10 flex max-w-full -translate-x-1/2 flex-col items-center gap-3">
              <div className="flex w-max max-w-full items-center gap-1 rounded-xl border border-[var(--border)] bg-[var(--bg-panel)] px-4 py-1 shadow-sm">
                <button disabled={proxyAction.busy} onClick={handleApplyProxy} className={`min-h-8 whitespace-nowrap rounded-lg border px-2 py-1.5 text-[10px] font-medium disabled:opacity-50 ${proxyStatus.known && proxyStatus.enabled ? 'border-[var(--accent)] bg-[var(--accent)] text-[var(--accent-text)] hover:bg-[var(--accent-hover)]' : 'border-[var(--border)] text-[var(--text-dim)] hover:bg-[var(--bg-hover)] hover:text-[var(--text)]'}`}>
                  {lang === 'zh' ? '设置代理' : 'Apply proxy'}
                </button>
                <button disabled={proxyAction.busy} onClick={handleClearProxy} className="min-h-8 whitespace-nowrap rounded-lg border border-[var(--border)] px-2 py-1.5 text-[10px] text-[var(--text-dim)] hover:bg-[var(--bg-hover)] hover:text-[var(--text)] disabled:opacity-50">
                  {lang === 'zh' ? '取消代理' : 'Clear proxy'}
                </button>
                <button onClick={handleCopyTerminalProxy} className="flex min-h-8 items-center justify-center gap-1.5 whitespace-nowrap rounded-lg border border-[var(--border)] px-2 py-1.5 text-[10px] text-[var(--text-dim)] hover:bg-[var(--bg-hover)] hover:text-[var(--text)]">
                  <Icon path={icons.copy} className="h-3.5 w-3.5 shrink-0" />
                  {lang === 'zh' ? '复制代理命令' : 'Copy proxy command'}
                </button>
                <div ref={ruleSelectorRef} className="relative shrink-0">
                  <button
                    disabled={!selected}
                    onClick={() => setRuleSelectorOpen((open) => !open)}
                    className="flex min-h-8 items-center justify-between gap-1.5 whitespace-nowrap rounded-lg border border-[var(--border)] px-2 text-left text-[10px] text-[var(--text-dim)] hover:bg-[var(--bg-hover)] disabled:cursor-not-allowed disabled:opacity-45"
                  >
                    <span>
                      {t('linkedOutboundRules')}
                      {selected && <span className="ml-2 text-[var(--text-faint)]">{(selected.outboundRuleIds || []).length}/{outboundRules.length}</span>}
                    </span>
                    <span className={`transition-transform ${ruleSelectorOpen ? 'rotate-180' : ''}`}>⌄</span>
                  </button>
                  {ruleSelectorOpen && selected && <>
                    <div className="absolute right-0 top-10 z-50 w-72 max-h-56 overflow-y-auto rounded-xl border border-[var(--border)] bg-[var(--bg-panel)] p-2 shadow-xl">
                      {outboundRules.length === 0 ? <div className="px-3 py-4 text-center text-[10px] text-[var(--text-faint)]">{lang === 'zh' ? '暂无出站规则，请先在出站页面创建' : 'No outbound rules. Create one on the Outbound page.'}</div> : outboundRules.map((rule) => {
                        const checked = (selected.outboundRuleIds || []).includes(rule.id)
                        return <button key={rule.id} onClick={() => toggleServerOutboundRule(rule.id)} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left hover:bg-[var(--bg-hover)]">
                          <span className={`flex h-4 w-4 items-center justify-center rounded border text-[10px] ${checked ? 'border-[var(--accent)] bg-[var(--accent)] text-white' : 'border-[var(--border-strong)]'}`}>{checked ? '✓' : ''}</span>
                          <span className="min-w-0 flex-1 truncate text-[10px] text-[var(--text)]">{rule.name}</span>
                          {!rule.enabled && <span className="text-[9px] text-[var(--text-faint)]">{lang === 'zh' ? '已停用' : 'Disabled'}</span>}
                        </button>
                      })}
                      {outboundRules.length > 0 && <div className="border-t border-[var(--border)] px-3 pt-2 text-[9px] text-[var(--text-faint)]">{lang === 'zh' ? '可多选，连接时自动合并所选规则' : 'Select multiple; linked rules are merged on connection.'}</div>}
                    </div>
                  </>}
                </div>
              </div>
              <div className="flex min-h-6 items-center gap-2">
                <div className="flex items-center gap-1.5 rounded-full bg-[var(--bg-elevated)] px-3 py-1 text-[9px] text-[var(--text-dim)] shadow-sm">
                  <span className={`h-1.5 w-1.5 rounded-full ${!proxyStatus.known ? 'bg-amber-400' : proxyStatus.enabled ? 'bg-emerald-400' : 'bg-[var(--text-faint)]'}`} />
                  {!proxyStatus.known
                    ? (lang === 'zh' ? '正在检查代理状态' : 'Checking proxy status')
                    : proxyStatus.enabled
                      ? (lang === 'zh' ? '系统代理已开启' : 'System proxy enabled')
                      : (lang === 'zh' ? '系统代理未开启' : 'System proxy disabled')}
                </div>
                {proxyAction.message && <div className="rounded-full bg-[var(--bg-elevated)] px-3 py-1 text-[9px] text-[var(--text-dim)] shadow-sm">{proxyAction.message}</div>}
              </div>
            </div>

            <div className="text-center panel-card px-8 py-4 min-w-[280px]">
              <div className="text-sm text-[var(--text-dim)]">{selected ? selected.name : t('noServerSelected')}</div>
              {selected && (
                <div className="text-xs text-[var(--text-faint)] mt-0.5">
                  {selected.protocol} · {selected.address}:{selected.port}
                </div>
              )}
            </div>

            {platform === 'windows' && !isRunning && (
              <div className="flex items-center rounded-lg bg-[var(--bg-panel)] border border-[var(--border)] p-1 text-xs">
                <button
                  onClick={() => setMode('proxy')}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md transition-colors ${mode === 'proxy' ? 'bg-[var(--accent)] text-[var(--accent-text)]' : 'text-[var(--text-dim)] hover:text-[var(--text)]'
                    }`}
                >
                  <Icon path={icons.globe} className="w-3.5 h-3.5" />
                  {t('proxy')}
                </button>
                <button
                  onClick={() => setMode('tun')}
                  className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md transition-colors ${mode === 'tun' ? 'bg-[var(--accent)] text-[var(--accent-text)]' : 'text-[var(--text-dim)] hover:text-[var(--text)]'
                    }`}
                >
                  <Icon path={icons.router} className="w-3.5 h-3.5" />
                  {t('tun')}
                </button>
              </div>
            )}

            {platform === 'windows' && !isRunning && (
              <label className="flex items-center gap-2 text-xs text-[var(--text-dim)] cursor-pointer select-none">
                <input
                  type="checkbox"
                  checked={killSwitch}
                  onChange={(e) => setKillSwitch(e.target.checked)}
                  className="w-3.5 h-3.5 rounded accent-[var(--accent)]"
                />
                <Icon path={icons.shield} className="w-3.5 h-3.5 text-[var(--text-faint)]" />
                {t('killSwitch')}
              </label>
            )}

            {platform === 'windows' && needsElevation && !isRunning && (
              <div className="flex items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--bg-panel)] px-3 py-2 text-xs text-[var(--text-dim)]">
                <Icon path={icons.shield} className="w-4 h-4 shrink-0 text-[var(--text-faint)]" />
                <span>{mode === 'tun' ? t('tunNeedsAdmin') : t('killSwitchNeedsAdmin')}</span>
                <button onClick={handleRestartElevated} className="text-[var(--accent)] hover:text-[var(--accent-hover)] font-medium shrink-0">
                  {t('restartAsAdmin')}
                </button>
              </div>
            )}

            <button
              onClick={handleToggle}
              disabled={isBusy || (!isRunning && !selected) || (needsElevation && !isRunning)}
              className={`relative w-40 h-40 rounded-full flex items-center justify-center transition-all duration-300 disabled:opacity-40 disabled:cursor-not-allowed ${isRunning
                ? 'bg-[var(--accent)] shadow-[0_0_60px_-10px_rgba(99,102,241,0.7)]'
                : 'bg-[var(--bg-panel)] border border-[var(--border-strong)] hover:border-[var(--text-faint)]'
                }`}
            >
              {isBusy ? (
                <div className="w-8 h-8 border-2 border-[var(--text-faint)] border-t-transparent rounded-full animate-spin" />
              ) : (
                <Icon path={icons.power} className={`w-12 h-12 ${isRunning ? 'text-[var(--accent-text)]' : 'text-[var(--text-faint)]'}`} />
              )}
            </button>

            <div className="text-center">
              <div className="text-sm font-medium">
                {isBusy ? (isRunning ? t('disconnecting') : t('connecting')) : isRunning ? t('connected') : t('disconnected')}
              </div>
              {isRunning && (
                <div className="text-xs text-[var(--text-faint)] mt-1">
                  {status.mode === 'tun' ? t('tunAdapterAllTraffic') : proxyEndpointSummary(persistedSettings.current?.ui?.proxyConfig)}
                </div>
              )}
            </div>

            {isRunning && (
              <button
                onClick={handleTest}
                disabled={testing}
                className="flex items-center gap-1.5 text-xs text-[var(--text-dim)] hover:text-[var(--text)] disabled:opacity-50 transition-colors"
              >
                <Icon path={icons.gauge} className="w-3.5 h-3.5" />
                {testing ? t('testing') : t('testConnection')}
              </button>
            )}

            <div className="w-full max-w-sm space-y-2">
              {error && (
                <div className="rounded-lg border border-[var(--danger-border)] bg-[var(--danger-bg)] px-3 py-2 text-xs text-[var(--danger)] break-words">
                  {error}
                </div>
              )}
              {testResult && testResult.ok && (
                <div className="rounded-lg border border-[var(--success-border)] bg-[var(--success-bg)] px-3 py-2 text-xs text-[var(--success)] flex items-center justify-center gap-2">
                  {testResult.country && (
                    <img
                      src={flagIconUrl(testResult.country)}
                      alt={testResult.country}
                      className="w-4 h-3 rounded-sm object-cover"
                      onError={(e) => { e.currentTarget.style.display = 'none' }}
                    />
                  )}
                  <span className="font-medium">{testResult.ip}</span>
                  {testResult.country && <span className="text-[var(--success)]/70">{testResult.country}</span>}
                  <span className="text-[var(--success)]/70">·</span>
                  <span>{testResult.delayMs}ms</span>
                </div>
              )}
              {testResult && !testResult.ok && (
                <div className="rounded-lg border border-[var(--danger-border)] bg-[var(--danger-bg)] px-3 py-2 text-xs text-[var(--danger)] break-words">
                  ✗ {testResult.text}
                </div>
              )}
            </div>

            {isRunning && (
              <div className="w-full max-w-sm rounded-lg border border-[var(--border)] bg-[var(--bg-panel)] overflow-hidden">
                <button
                  onClick={() => setTrafficOpen((v) => !v)}
                  className="w-full flex items-center justify-center gap-1.5 px-3 py-2 text-xs text-[var(--text-dim)] hover:text-[var(--text)] transition-colors"
                >
                  <Icon path={trafficOpen ? 'm18 15-6-6-6 6' : 'm6 9 6 6 6-6'} className="w-3.5 h-3.5" />
                  {trafficOpen ? t('showLess') : t('showMore')}
                </button>
                {trafficOpen && (
                  <div className="border-t border-[var(--border)] divide-y divide-[var(--border)]">
                    <div className="px-3 py-2">
                      <div className="text-[11px] text-[var(--text-faint)] mb-1">{t('liveTraffic')}</div>
                      <div className="flex items-center justify-between text-xs">
                        <span className="flex items-center gap-1 text-[var(--success)]">
                          <Icon path="M12 19V5M5 12l7-7 7 7" className="w-3 h-3" />
                          {formatSpeed(speed.up)}
                        </span>
                        <span className="flex items-center gap-1 text-[var(--danger)]">
                          <Icon path="M12 5v14M5 12l7 7 7-7" className="w-3 h-3" />
                          {formatSpeed(speed.down)}
                        </span>
                      </div>
                    </div>
                    <div className="px-3 py-2">
                      <div className="text-[11px] text-[var(--text-faint)] mb-1">{t('totalTraffic')}</div>
                      <div className="flex items-center justify-between text-xs">
                        <span className="flex items-center gap-1 text-[var(--success)]">
                          <Icon path="M12 19V5M5 12l7-7 7 7" className="w-3 h-3" />
                          {formatBytes(traffic.uplink)}
                        </span>
                        <span className="flex items-center gap-1 text-[var(--danger)]">
                          <Icon path="M12 5v14M5 12l7 7 7-7" className="w-3 h-3" />
                          {formatBytes(traffic.downlink)}
                        </span>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )}

          </main>
        </>}
      </div>

      {notice && (
        <div className="fixed bottom-5 left-1/2 -translate-x-1/2 z-50 rounded-lg bg-[var(--accent)] text-[var(--accent-text)] px-4 py-2 text-xs shadow-lg">
          {notice}
        </div>
      )}

      {editServer && (
        <ServerEditor initial={editServer} t={t} onCancel={() => setEditServer(null)} onSave={handleSaveServer} />
      )}

      {editGroup && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setEditGroup(null)}>
          <div
            className="w-full max-w-sm rounded-xl bg-[var(--bg-panel)] border border-[var(--border)] p-5 space-y-3"
            onClick={(e) => e.stopPropagation()}
          >
            <h2 className="text-sm font-semibold">{t('editSubscription')}</h2>
            <label className="block text-xs text-[var(--text-dim)]">
              {t('name')}
              <input
                {...noTextAssist}
                autoFocus
                className="mt-1 w-full rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)] px-3 py-2 text-sm focus:outline-none focus:border-[var(--accent)]"
                value={editGroup.name}
                onChange={(e) => setEditGroup({ ...editGroup, name: e.target.value })}
              />
            </label>
            <label className="block text-xs text-[var(--text-dim)]">
              {t('subscriptionUrl')}
              <input
                {...noTextAssist}
                className="mt-1 w-full rounded-lg bg-[var(--bg-elevated)] border border-[var(--border)] px-3 py-2 text-xs focus:outline-none focus:border-[var(--accent)]"
                value={editGroup.url}
                onChange={(e) => setEditGroup({ ...editGroup, url: e.target.value })}
                onKeyDown={(e) => e.key === 'Enter' && handleSaveGroup()}
              />
            </label>
            <div className="flex justify-end gap-2 pt-1">
              <button className="text-xs px-3 py-1.5 rounded-md hover:bg-[var(--bg-hover)]" onClick={() => setEditGroup(null)}>
                {t('cancel')}
              </button>
              <button
                className="text-xs px-3 py-1.5 rounded-md bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-[var(--accent-text)]"
                onClick={handleSaveGroup}
              >
                {t('save')}
              </button>
            </div>
          </div>
        </div>
      )}

      {aboutOpen && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setAboutOpen(false)}>
          <div
            className="w-full max-w-sm rounded-xl bg-[var(--bg-panel)] border border-[var(--border)] p-6 text-center"
            onClick={(e) => e.stopPropagation()}
          >
            <img src={logo} alt="Krab" className="w-16 h-16 rounded-full object-cover ring-1 ring-[var(--border)] shadow-lg mx-auto mb-4" />
            <h2 className="text-lg font-semibold">Krab</h2>
            <p className="text-xs text-[var(--text-faint)] mt-1">
              v{version.replace(/^v/, '')}
              {xrayVersion && <> · xray-core {xrayVersion}</>}
            </p>
            <p className="text-sm text-[var(--text-dim)] mt-4">
              {t('aboutDescription')}
            </p>

            <div
              className="mt-4 flex items-center justify-center gap-2 rounded-md border border-[var(--border-strong)] px-3 py-1.5 cursor-pointer hover:bg-[var(--bg-hover)] transition-colors"
              onClick={() => navigator.clipboard?.writeText('https://github.com/krabt/krab')}
              title={t('clickToCopy')}
            >
              <span className="text-xs text-[var(--accent)]">github.com/krabt/krab</span>
              <Icon path="M8 16H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2m-6 12h8a2 2 0 0 0 2-2v-8a2 2 0 0 0-2-2h-8a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2Z" className="w-3.5 h-3.5 text-[var(--text-faint)]" />
            </div>

            <div className="mt-3 flex items-center justify-center gap-4 text-xs">
              <button
                className="text-[var(--text-dim)] hover:text-[var(--accent)] underline underline-offset-2"
                onClick={() => openExternal('https://github.com/krabt/krab')}
              >
                {t('repository')}
              </button>
              <button
                className="text-[var(--text-dim)] hover:text-[var(--accent)] underline underline-offset-2"
                onClick={() => openExternal('https://github.com/krabt/krab/releases')}
              >
                {t('releases')}
              </button>
              <button
                className="text-[var(--text-dim)] hover:text-[var(--accent)] underline underline-offset-2"
                onClick={() => openExternal('https://github.com/krabt/krab/issues')}
              >
                {t('reportIssue')}
              </button>
            </div>

            <p className="mt-3 text-center text-[10px] text-[var(--text-faint)]">
              {t('searchHint')}
            </p>

            <div className="mt-5 pt-4 border-t border-[var(--border)]">
              <button
                onClick={handleCheckUpdate}
                disabled={checkingUpdate}
                className="text-xs rounded-md border border-[var(--border-strong)] hover:bg-[var(--bg-hover)] px-3 py-1.5 disabled:opacity-50 transition-colors"
              >
                {checkingUpdate ? t('checking') : t('checkForUpdates')}
              </button>
              {updateInfo && (
                <p className="text-xs text-[var(--text-faint)] mt-2">
                  {updateInfo.available ? t('updateAvailable', updateInfo.latest) : t('onLatest')}
                </p>
              )}
            </div>

            <button
              className="mt-5 text-xs text-[var(--text-faint)] hover:text-[var(--text)]"
              onClick={() => setAboutOpen(false)}
            >
              {t('close')}
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
